import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = resolve(__dirname, '../src/data/words.json');

// Read existing words
const existingWords = JSON.parse(readFileSync(dataPath, 'utf-8'));
const existingSet = new Set(existingWords.map(w => w.word.toLowerCase()));

// Final batch to reach 1000 words
const finalWords = [
  ["ambrosial", "adjective", "Worthy of the gods; delicious", "Ambrosial aromas filled the kitchen.", "The ambrosial nectar refreshed them."],
  ["nectarous", "adjective", "Sweet like nectar", "Nectarous fruit delighted the palate.", "The nectarous drink was divine."],
  ["savorous", "adjective", "Pleasing to the taste", "Savorous dishes tempted diners.", "The savorous meal was memorable."],
  ["sapid", "adjective", "Having a pleasant taste", "Sapid herbs enhanced the dish.", "The sapid wine paired perfectly."],
  ["palatable", "adjective", "Pleasant to taste", "The medicine was barely palatable.", "Palatable options were offered."],
  ["appetizing", "adjective", "Stimulating the appetite", "Appetizing smells drew crowds.", "The appetizing display tempted shoppers."],
  ["succulent", "adjective", "Juicy and tender", "Succulent fruit burst with flavor.", "The succulent roast impressed guests."],
  ["luscious", "adjective", "Richly sweet in taste", "Luscious berries filled the basket.", "The luscious dessert was heavenly."],
  ["voluptuous", "adjective", "Relating to sensual pleasure", "Voluptuous curves defined the sculpture.", "The voluptuous fabric draped beautifully."],
  ["sensuous", "adjective", "Relating to the senses", "Sensuous textures invited touch.", "The sensuous melody enchanted listeners."],
  ["tactile", "adjective", "Relating to the sense of touch", "Tactile experiences enhanced learning.", "The tactile quality was pleasing."],
  ["palpable", "adjective", "Able to be touched or felt", "Tension was palpable in the room.", "Her excitement was palpable."],
  ["tangible", "adjective", "Perceptible by touch", "Tangible results were demanded.", "The tangible evidence convinced the jury."],
  ["visceral", "adjective", "Relating to deep feelings", "A visceral reaction overcame her.", "The visceral impact was powerful."],
  ["primal", "adjective", "Relating to early stages", "Primal instincts took over.", "Primal forces shaped the landscape."],
  ["elemental", "adjective", "Fundamental; relating to elements", "Elemental forces were at work.", "The elemental beauty was stark."],
  ["primordial", "adjective", "Existing from the beginning", "Primordial ooze spawned life.", "Primordial fears lurked within."],
  ["nascent", "adjective", "Just beginning to develop", "Nascent ideas needed nurturing.", "The nascent movement gained momentum."],
  ["incipient", "adjective", "Beginning to happen or develop", "Incipient signs of change appeared.", "Her incipient smile encouraged him."],
  ["emergent", "adjective", "In the process of coming into being", "Emergent technologies disrupted industries.", "The emergent trend was noted."],
  ["burgeoning", "adjective", "Beginning to grow rapidly", "Burgeoning interest surprised analysts.", "The burgeoning city expanded outward."],
  ["flourishing", "adjective", "Developing rapidly and successfully", "Flourishing businesses lined the street.", "The flourishing arts scene attracted visitors."],
  ["thriving", "adjective", "Prospering and growing", "Thriving communities supported each other.", "The thriving economy created jobs."],
  ["prosperous", "adjective", "Successful in material terms", "Prosperous families built grand homes.", "The prosperous era was remembered fondly."],
  ["affluent", "adjective", "Having a great deal of money", "Affluent neighborhoods commanded high prices.", "Affluent donors supported the cause."],
  ["opulent", "adjective", "Ostentatiously rich and luxurious", "Opulent decorations filled the ballroom.", "The opulent lifestyle attracted attention."],
  ["resplendent", "adjective", "Impressive through rich colors", "Resplendent robes marked the ceremony.", "The resplendent sunset painted the sky."],
  ["effulgent", "adjective", "Shining brightly", "Effulgent light filled the chamber.", "Her effulgent smile warmed hearts."],
  ["refulgent", "adjective", "Shining very brightly", "Refulgent glory crowned the victor.", "The refulgent display amazed spectators."],
  ["coruscating", "adjective", "Sparkling or gleaming", "Coruscating gems adorned the crown.", "His coruscating wit entertained all."],
  ["scintillant", "adjective", "Sparkling or twinkling", "Scintillant stars filled the sky.", "Her scintillant eyes danced with joy."],
  ["twinkling", "adjective", "Shining with a fluctuating light", "Twinkling lights decorated the tree.", "His twinkling eyes revealed mischief."],
  ["glinting", "adjective", "Giving out small flashes of light", "Glinting water reflected the sun.", "The glinting sword caught his eye."],
  ["glistening", "adjective", "Shining with reflected light", "Glistening dew covered the grass.", "Her glistening tears moved him."],
  ["glimmering", "adjective", "Shining faintly with a wavering light", "Glimmering hope sustained them.", "Glimmering lights dotted the shore."],
  ["gleaming", "adjective", "Shining brightly", "Gleaming floors reflected the light.", "The gleaming trophy was displayed proudly."],
  ["shimmering", "adjective", "Shining with a soft trembling light", "Shimmering heat rose from the pavement.", "The shimmering lake was beautiful."],
  ["glistering", "adjective", "Sparkling or glistening", "Glistering frost covered the window.", "Glistering jewels adorned her."],
  ["resplendence", "noun", "Brilliant and impressive appearance", "The resplendence of the palace awed visitors.", "Nature's resplendence inspired the poet."],
  ["magnificence", "noun", "The quality of being magnificent", "The magnificence of the cathedral impressed all.", "Royal magnificence was on display."],
  ["grandeur", "noun", "Splendor and impressiveness", "The grandeur of the mountains humbled them.", "Faded grandeur marked the old estate."],
  ["majesty", "noun", "Impressive beauty and dignity", "The majesty of nature inspired awe.", "Royal majesty commanded respect."],
  ["splendor", "noun", "Magnificent and impressive beauty", "The splendor of the garden amazed visitors.", "Ancient splendor lay in ruins."],
  ["glory", "noun", "High renown or honor", "Glory awaited the victorious.", "The glory of the sunset faded."],
  ["brilliance", "noun", "Exceptional talent or intelligence", "Her brilliance was widely recognized.", "The brilliance of the gem was unmatched."],
  ["radiance", "noun", "Light emanating from something", "The radiance of her smile warmed hearts.", "Morning radiance flooded the room."],
  ["luminescence", "noun", "Light emission not caused by heat", "The luminescence of the jellyfish amazed divers.", "Strange luminescence lit the cave."],
  ["incandescence", "noun", "Light produced by high temperature", "The incandescence of the forge lit the smithy.", "Volcanic incandescence glowed in the night."],
  ["phosphorescence", "noun", "Light emitted without combustion", "Phosphorescence made the water glow.", "The phosphorescence faded slowly."],
  ["bioluminescence", "noun", "Light produced by living organisms", "Bioluminescence illuminated the deep ocean.", "The bioluminescence was magical to witness."],
  ["fluorescence", "noun", "Light emission during radiation exposure", "Fluorescence revealed the hidden ink.", "The mineral's fluorescence was unusual."],
  ["opalescence", "noun", "A milky iridescence", "The opalescence of the gem was unique.", "Opalescence characterized the moonstone."],
  ["iridescence", "noun", "A lustrous rainbow-like play of color", "The iridescence of the peacock amazed viewers.", "Soap bubbles showed beautiful iridescence."],
  ["nacreous", "adjective", "Resembling mother of pearl", "Nacreous clouds appeared at dawn.", "The nacreous shell gleamed."],
  ["lustrous", "adjective", "Having luster; shining", "Lustrous pearls adorned her neck.", "His lustrous coat shone in the sun."],
  ["satiny", "adjective", "Smooth and glossy like satin", "Satiny petals felt soft to the touch.", "Her satiny skin glowed."],
  ["silken", "adjective", "Made of or resembling silk", "Silken threads bound the book.", "Her silken hair flowed freely."],
  ["gossamer", "adjective", "Very light, thin, and insubstantial", "Gossamer wings caught the light.", "Gossamer clouds drifted overhead."],
  ["diaphanous", "adjective", "Light, delicate, and translucent", "Diaphanous curtains filtered the light.", "She wore a diaphanous gown."],
  ["filmy", "adjective", "Covered with or resembling a thin film", "Filmy curtains softened the light.", "A filmy haze covered the valley."],
  ["gauzy", "adjective", "Resembling gauze; thin and translucent", "Gauzy fabric swayed in the breeze.", "A gauzy mist rose from the lake."],
  ["wispy", "adjective", "Fine and feathery", "Wispy clouds streaked the sky.", "Wispy tendrils of hair framed her face."],
  ["ethereal", "adjective", "Extremely delicate and light", "An ethereal beauty characterized her.", "Ethereal music filled the cathedral."],
  ["airy", "adjective", "Light and graceful", "Airy rooms felt spacious.", "Her airy manner put people at ease."],
  ["vaporous", "adjective", "Resembling vapor", "Vaporous mist shrouded the valley.", "Vaporous dreams faded upon waking."],
  ["nebular", "adjective", "Relating to a nebula or cloud", "Nebular formations fascinated astronomers.", "The nebular hypothesis explained planets."],
  ["celestial", "adjective", "Positioned in or relating to the sky", "Celestial navigation guided ancient sailors.", "Celestial beauty inspired poets."],
  ["astral", "adjective", "Relating to or resembling the stars", "Astral projections fascinated her.", "The astral plane called to mystics."],
  ["stellar", "adjective", "Relating to a star or stars", "Stellar performances earned acclaim.", "The stellar display amazed astronomers."],
  ["sidereal", "adjective", "Of or with respect to the stars", "Sidereal time differs from solar time.", "Sidereal observations guided the research."],
  ["cosmic", "adjective", "Relating to the universe", "Cosmic forces shaped galaxies.", "A cosmic perspective humbled observers."],
  ["universal", "adjective", "Relating to the whole universe", "Universal truths transcend cultures.", "Universal acclaim greeted the film."],
  ["infinite", "adjective", "Limitless in space or extent", "Infinite possibilities awaited.", "The infinite stars fascinated her."],
  ["boundless", "adjective", "Without limits", "Boundless energy characterized her.", "His boundless enthusiasm was infectious."],
  ["limitless", "adjective", "Without end or limit", "Limitless potential was recognized.", "The ocean seemed limitless."],
  ["illimitable", "adjective", "Without limits or end", "Illimitable horizons stretched before them.", "His illimitable imagination created worlds."],
  ["measureless", "adjective", "Having no bounds", "Measureless caverns extended underground.", "His measureless grief consumed him."],
  ["unfathomable", "adjective", "Incapable of being fully understood", "The unfathomable depths hid secrets.", "Her unfathomable wisdom guided the village."],
  ["immeasurable", "adjective", "Too large to measure", "Immeasurable gratitude was expressed.", "The immeasurable universe awed scientists."],
  ["incalculable", "adjective", "Too great to be calculated", "Incalculable losses were suffered.", "The discovery had incalculable value."],
  ["inestimable", "adjective", "Too great to calculate", "Her contribution was of inestimable value.", "Inestimable damage was prevented."],
  ["invaluable", "adjective", "Extremely useful; indispensable", "His advice proved invaluable.", "Invaluable lessons were learned."],
  ["priceless", "adjective", "So precious that no price can be set", "Priceless artifacts were protected.", "The priceless moment was captured."],
  ["precious", "adjective", "Of great value", "Precious memories were treasured.", "The precious stone was flawless."],
  ["exquisite", "adjective", "Extremely beautiful and delicate", "Exquisite workmanship defined the piece.", "Her exquisite taste was renowned."],
  ["delicate", "adjective", "Very fine in texture", "Delicate fabrics required care.", "A delicate balance was maintained."],
  ["dainty", "adjective", "Delicately small and pretty", "Dainty teacups lined the shelf.", "Her dainty fingers moved quickly."],
  ["petite", "adjective", "Attractively small and dainty", "The petite dancer moved gracefully.", "Petite portions were served."],
  ["diminutive", "adjective", "Extremely small", "A diminutive figure emerged from shadows.", "The diminutive bird had a mighty voice."],
  ["minute", "adjective", "Extremely small", "Minute details revealed the forgery.", "Minute adjustments were made."],
  ["minuscule", "adjective", "Extremely small", "Minuscule organisms were discovered.", "The minuscule difference mattered."],
  ["microscopic", "adjective", "So small as to be visible only with a microscope", "Microscopic life teemed in the drop.", "Microscopic analysis revealed flaws."],
  ["infinitesimal", "adjective", "Extremely small", "Infinitesimal chances remained.", "The infinitesimal error compounded."],
  ["imperceptible", "adjective", "Impossible to perceive", "Imperceptible changes accumulated.", "His imperceptible nod signaled agreement."],
  ["indiscernible", "adjective", "Impossible to see or clearly distinguish", "The difference was indiscernible.", "Indiscernible sounds hinted at presence."],
  ["inconspicuous", "adjective", "Not clearly visible or attracting attention", "She preferred to remain inconspicuous.", "The inconspicuous entrance was hard to find."],
  ["unobtrusive", "adjective", "Not conspicuous or attracting attention", "Unobtrusive service characterized the staff.", "Her unobtrusive presence was calming."],
  ["discreet", "adjective", "Careful to avoid attention", "Discreet inquiries were made.", "A discreet distance was maintained."],
  ["subtle", "adjective", "Delicate or precise as to be difficult to analyze", "Subtle hints were dropped.", "The subtle fragrance lingered."],
  ["nuanced", "adjective", "Characterized by subtle shades of meaning", "Nuanced performances earned critical acclaim.", "A nuanced approach was required."],
  ["refined", "adjective", "With impurities removed; elegant", "Refined manners impressed the host.", "Her refined taste was evident."],
  ["polished", "adjective", "Shiny from rubbing; accomplished", "Polished performances concluded the show.", "His polished manner charmed everyone."],
  ["suave", "adjective", "Charming, confident, and elegant", "The suave diplomat negotiated skillfully.", "His suave manner won admiration."],
  ["debonair", "adjective", "Confident, stylish, and charming", "The debonair gentleman attracted attention.", "His debonair attitude was admired."],
  ["urbane", "adjective", "Suave, courteous, and refined", "Urbane conversation flowed at the dinner.", "His urbane wit entertained guests."],
  ["cosmopolitan", "adjective", "Familiar with many countries and cultures", "Cosmopolitan tastes characterized the traveler.", "The cosmopolitan city welcomed all."],
  ["worldly", "adjective", "Experienced in human society", "Worldly wisdom guided her decisions.", "His worldly manner impressed colleagues."],
  ["sophisticated", "adjective", "Having refined tastes and habits", "Sophisticated palates appreciated the wine.", "A sophisticated approach was needed."],
  ["cultured", "adjective", "Characterized by refined taste", "Cultured conversation enriched the evening.", "Her cultured voice was soothing."],
  ["cultivated", "adjective", "Refined and well-educated", "Cultivated sensibilities guided her choices.", "The cultivated garden flourished beautifully."],
  ["genteel", "adjective", "Polite, refined, or respectable", "Genteel society gathered at the club.", "Her genteel manner was admired."],
  ["elegant", "adjective", "Pleasingly graceful and stylish", "Elegant solutions emerged from discussion.", "Her elegant attire impressed everyone."],
  ["gracious", "adjective", "Courteous, kind, and pleasant", "The gracious host welcomed all guests.", "Her gracious manner put everyone at ease."],
  ["courteous", "adjective", "Polite, respectful, and considerate", "Courteous service was appreciated.", "His courteous behavior was noted."],
  ["civil", "adjective", "Courteous and polite", "Civil discourse was encouraged.", "A civil response was given."],
  ["cordial", "adjective", "Warm and friendly", "A cordial welcome awaited visitors.", "Cordial relations were established."],
  ["affable", "adjective", "Friendly, good-natured, and easy to talk to", "The affable professor was popular.", "His affable nature won friends."],
  ["amiable", "adjective", "Having a friendly and pleasant manner", "The amiable neighbor offered help.", "Her amiable disposition was appreciated."],
  ["genial", "adjective", "Friendly and cheerful", "A genial smile greeted newcomers.", "His genial manner put people at ease."],
  ["congenial", "adjective", "Pleasant because of shared interests", "Congenial company made the journey pleasant.", "The congenial atmosphere encouraged sharing."],
  ["convivial", "adjective", "Friendly, lively, and enjoyable", "Convivial gatherings were frequent.", "The convivial host kept spirits high."],
  ["jovial", "adjective", "Cheerful and friendly", "Jovial laughter filled the room.", "His jovial nature was infectious."],
  ["blithe", "adjective", "Showing a casual and cheerful indifference", "A blithe spirit characterized her.", "Blithe disregard for rules annoyed some."],
  ["merry", "adjective", "Cheerful and lively", "Merry laughter echoed through the halls.", "A merry band of friends gathered."],
  ["gleeful", "adjective", "Exuberantly joyful", "Gleeful children played in the yard.", "A gleeful shout announced victory."],
  ["mirthful", "adjective", "Full of mirth", "Mirthful sounds filled the party.", "Her mirthful eyes sparkled."],
  ["joyous", "adjective", "Full of happiness and joy", "Joyous celebrations marked the occasion.", "A joyous reunion followed."],
  ["jubilant", "adjective", "Feeling or expressing great happiness", "Jubilant crowds filled the streets.", "The jubilant team celebrated victory."],
  ["elated", "adjective", "Ecstatically happy", "She was elated by the news.", "Elated fans cheered wildly."],
  ["ecstatic", "adjective", "Feeling overwhelming happiness", "Ecstatic applause greeted the performer.", "She was ecstatic about the promotion."],
  ["euphoric", "adjective", "Characterized by intense feelings of well-being", "A euphoric mood spread through the crowd.", "The euphoric sensation faded slowly."],
  ["blissful", "adjective", "Extremely happy; full of joy", "Blissful days passed quickly.", "A blissful smile crossed her face."],
  ["rapturous", "adjective", "Characterized by ecstatic joy", "Rapturous applause followed the performance.", "Rapturous reviews greeted the album."],
  ["enraptured", "adjective", "Filled with delight", "The enraptured audience sat in silence.", "He was enraptured by her beauty."],
  ["enchanted", "adjective", "Filled with delight; charmed", "The enchanted forest beckoned.", "She was enchanted by the fairy tale."],
  ["captivated", "adjective", "Attracted and held the attention of", "Captivated by the story, they listened.", "The captivated audience sat still."],
  ["enthralled", "adjective", "Charmed and held spellbound", "Enthralled viewers watched the finale.", "She was enthralled by his stories."],
  ["fascinated", "adjective", "Strongly attracted and interested", "Fascinated by the discovery, they investigated.", "The fascinated child asked questions."],
  ["intrigued", "adjective", "Aroused the curiosity or interest of", "Intrigued by the mystery, she explored.", "The intrigued investigator dug deeper."],
  ["curious", "adjective", "Eager to know or learn something", "Curious minds asked questions.", "A curious expression crossed her face."],
  ["inquisitive", "adjective", "Curious or inquiring", "Inquisitive students learned more.", "His inquisitive nature led to discoveries."],
  ["questioning", "adjective", "Showing an interest in learning", "A questioning look invited explanation.", "Questioning minds drove progress."],
  ["inquiring", "adjective", "Showing a wish to learn", "Inquiring reporters sought answers.", "An inquiring mind is valuable."],
  ["searching", "adjective", "Examining thoroughly", "Searching questions revealed the truth.", "Her searching gaze made him uncomfortable."],
  ["probing", "adjective", "Inquiring closely", "Probing questions uncovered facts.", "His probing analysis was thorough."],
  ["penetrating", "adjective", "Able to make way into or through", "Penetrating insight characterized her work.", "A penetrating gaze fixed on him."],
  ["piercing", "adjective", "Very sharp or intense", "Piercing eyes studied the crowd.", "A piercing cry broke the silence."],
  ["keen", "adjective", "Having a sharp edge or point", "Keen observation revealed details.", "Her keen mind impressed everyone."],
  ["acute", "adjective", "Present or experienced to a severe degree", "Acute awareness saved him.", "The acute angle was precisely measured."],
  ["sharp", "adjective", "Having a fine cutting edge or point", "A sharp mind solved the puzzle.", "Sharp criticism followed the decision."],
  ["trenchant", "adjective", "Vigorous or incisive in expression", "Trenchant criticism stung the author.", "His trenchant analysis cut through confusion."],
  ["incisive", "adjective", "Intelligently analytical and clear-thinking", "Incisive commentary illuminated issues.", "Her incisive questions revealed truth."],
  ["discerning", "adjective", "Having good judgment", "Discerning buyers appreciated quality.", "Her discerning eye caught the flaw."],
  ["perceptive", "adjective", "Having a ready insight into things", "Perceptive observation guided her.", "His perceptive comments helped."],
  ["insightful", "adjective", "Having deep understanding", "Insightful analysis proved valuable.", "Her insightful remarks impressed everyone."],
  ["astute", "adjective", "Having an ability to notice and understand", "Astute observers noticed the change.", "His astute mind grasped complexities."],
  ["shrewd", "adjective", "Having sharp judgment", "Shrewd investors profited.", "Her shrewd assessment was accurate."],
  ["sagacious", "adjective", "Having keen mental discernment", "Sagacious leaders anticipated problems.", "His sagacious advice was sought."],
  ["sapient", "adjective", "Wise or attempting to appear wise", "Sapient beings pondered existence.", "His sapient observations guided the discussion."],
  ["wise", "adjective", "Having knowledge and good judgment", "Wise counsel was appreciated.", "The wise elder shared stories."],
  ["judicious", "adjective", "Having good judgment or sense", "Judicious use of resources was required.", "Her judicious decisions were respected."],
  ["prudent", "adjective", "Acting with care for the future", "Prudent planning prevented problems.", "Prudent investments paid off."],
  ["sensible", "adjective", "Done with good judgment", "A sensible approach was taken.", "Sensible advice was appreciated."],
  ["reasonable", "adjective", "Having sound judgment", "Reasonable expectations were set.", "A reasonable solution was found."],
  ["rational", "adjective", "Based on reason or logic", "Rational arguments prevailed.", "A rational approach was adopted."],
  ["logical", "adjective", "Of or according to the rules of logic", "Logical analysis guided decisions.", "A logical conclusion was reached."],
  ["coherent", "adjective", "Logical and consistent", "A coherent argument was presented.", "His coherent explanation clarified matters."],
  ["lucid", "adjective", "Expressed clearly", "Lucid prose characterized his writing.", "Her lucid explanation helped students."],
  ["perspicuous", "adjective", "Clearly expressed and easily understood", "Perspicuous writing aided comprehension.", "The perspicuous instructions helped users."],
  ["pellucid", "adjective", "Translucently clear", "Pellucid waters revealed the bottom.", "His pellucid prose was admired."],
  ["limpid", "adjective", "Free of anything that darkens", "Limpid streams flowed through the valley.", "Her limpid gaze revealed sincerity."],
  ["crystalline", "adjective", "Very clear", "Crystalline clarity characterized her voice.", "The crystalline logic was impressive."],
  ["transparent", "adjective", "Allowing light to pass through", "Transparent motives were obvious.", "The transparent process built trust."],
  ["translucent", "adjective", "Allowing light to pass through diffusely", "Translucent panels softened the light.", "The translucent material was beautiful."],
  ["luminous", "adjective", "Full of or shedding light", "Luminous eyes gazed at the stars.", "Her luminous smile brightened the room."],
  ["radiant", "adjective", "Sending out light; shining brightly", "Her radiant beauty captivated all.", "Radiant sunshine warmed the garden."],
  ["beaming", "adjective", "Shining brightly; radiating", "Beaming smiles greeted the news.", "His beaming face showed pride."],
  ["glowing", "adjective", "Expressing great praise", "Glowing reviews praised the film.", "Her glowing complexion was envied."],
  ["blazing", "adjective", "Burning fiercely", "Blazing sunlight scorched the earth.", "His blazing eyes showed anger."],
  ["dazzling", "adjective", "Extremely bright", "Dazzling light blinded momentarily.", "Her dazzling performance won acclaim."],
  ["blinding", "adjective", "Very bright", "Blinding flash illuminated the scene.", "His blinding speed amazed spectators."],
  ["brilliant", "adjective", "Exceptionally clever or talented", "Brilliant ideas transformed the field.", "Her brilliant strategy succeeded."],
  ["scintillating", "adjective", "Sparkling or shining brightly", "Scintillating wit entertained guests.", "The scintillating performance dazzled all."],
  ["coruscating", "adjective", "Flashing or sparkling", "Coruscating jewels adorned her.", "His coruscating intellect impressed scholars."],
  ["effulgent", "adjective", "Shining brightly; radiant", "Effulgent rays warmed the morning.", "Her effulgent beauty lit up the room."],
  ["resplendent", "adjective", "Impressive through being richly colorful", "Resplendent plumage marked the bird.", "The resplendent bride glided down the aisle."],
  ["magnificent", "adjective", "Extremely beautiful, elaborate, or impressive", "Magnificent architecture dominated the city.", "A magnificent performance closed the show."],
  ["majestic", "adjective", "Having grandeur", "Majestic mountains rose in the distance.", "The majestic lion surveyed his domain."],
  ["glorious", "adjective", "Having great beauty and splendor", "A glorious sunset painted the sky.", "Glorious victory was celebrated."],
  ["splendiferous", "adjective", "Splendid", "A splendiferous feast awaited guests.", "The splendiferous display amazed visitors."],
  ["wondrous", "adjective", "Inspiring a feeling of wonder", "Wondrous sights awaited explorers.", "The wondrous beauty left them speechless."],
  ["marvelous", "adjective", "Causing great wonder", "Marvelous discoveries changed understanding.", "A marvelous achievement was recognized."],
  ["stupendous", "adjective", "Extremely impressive", "Stupendous effort achieved the impossible.", "The stupendous view took their breath away."],
  ["prodigious", "adjective", "Remarkably great in extent", "Prodigious talent was evident.", "His prodigious output amazed colleagues."],
  ["phenomenal", "adjective", "Remarkable or exceptional", "Phenomenal success followed the release.", "Her phenomenal rise inspired many."],
  ["extraordinary", "adjective", "Very unusual or remarkable", "Extraordinary circumstances warranted action.", "His extraordinary gifts were celebrated."],
  ["exceptional", "adjective", "Unusually good", "Exceptional quality defined the brand.", "Her exceptional performance was noted."],
  ["outstanding", "adjective", "Exceptionally good", "Outstanding results exceeded expectations.", "His outstanding contribution was recognized."],
  ["remarkable", "adjective", "Worthy of attention", "Remarkable progress was made.", "Her remarkable story inspired many."],
  ["notable", "adjective", "Worthy of attention or notice", "Notable achievements were honored.", "The notable exception proved the rule."],
  ["noteworthy", "adjective", "Interesting or significant", "Noteworthy developments were reported.", "Her noteworthy efforts were appreciated."],
  ["memorable", "adjective", "Worth remembering", "Memorable experiences enriched life.", "A memorable performance closed the season."],
  ["unforgettable", "adjective", "Impossible to forget", "An unforgettable journey changed her.", "The unforgettable moment was captured."],
  ["indelible", "adjective", "Making marks that cannot be removed", "Indelible impressions were made.", "The indelible memory remained."],
  ["enduring", "adjective", "Lasting over time", "Enduring love sustained them.", "His enduring legacy influenced generations."],
  ["lasting", "adjective", "Continuing for a long time", "Lasting peace was achieved.", "A lasting impression was made."],
  ["perpetual", "adjective", "Never ending or changing", "Perpetual motion remains theoretical.", "His perpetual optimism was admired."],
  ["eternal", "adjective", "Lasting forever", "Eternal truths transcend time.", "Their eternal bond was unbreakable."],
  ["everlasting", "adjective", "Lasting forever", "Everlasting gratitude was expressed.", "The everlasting flame burned bright."],
  ["immortal", "adjective", "Living forever", "Immortal fame was achieved.", "His immortal works endured."],
  ["timeless", "adjective", "Not affected by time", "Timeless beauty characterized the design.", "The timeless classic entertained generations."],
  ["ageless", "adjective", "Never looking old", "Ageless elegance defined her style.", "The ageless wisdom guided them."],
  ["perennial", "adjective", "Lasting for an indefinite time", "Perennial favorites returned each year.", "The perennial question remained unanswered."],
  ["quintessential", "adjective", "Representing the most perfect example", "The quintessential summer day arrived.", "She was the quintessential professional."],
  ["archetypal", "adjective", "Very typical of a certain kind", "An archetypal hero's journey unfolded.", "The archetypal villain appeared."],
  ["classic", "adjective", "Judged over time to be of highest quality", "Classic design never goes out of style.", "The classic tale enchanted readers."],
  ["paradigmatic", "adjective", "Serving as a typical example", "A paradigmatic case was studied.", "Her career was paradigmatic of dedication."],
  ["exemplary", "adjective", "Serving as a desirable model", "Exemplary conduct was rewarded.", "His exemplary service was recognized."],
  ["model", "adjective", "Used as an example to follow", "A model student excelled in all areas.", "The model employee received a bonus."],
  ["ideal", "adjective", "Satisfying one's conception of what is perfect", "Ideal conditions prevailed.", "The ideal solution was found."],
  ["perfect", "adjective", "Having all required qualities", "Perfect timing saved the day.", "The perfect match was made."],
  ["flawless", "adjective", "Without any blemishes", "A flawless performance earned standing ovation.", "The flawless diamond sparkled."],
  ["immaculate", "adjective", "Perfectly clean or pure", "Immaculate presentation impressed the judges.", "Her immaculate record stood out."]
];

// Add new words if not already present
let addedCount = 0;
for (const [word, pos, definition, ex1, ex2] of finalWords) {
  if (!existingSet.has(word.toLowerCase())) {
    existingWords.push({
      word,
      pos,
      definition,
      examples: [ex1, ex2]
    });
    existingSet.add(word.toLowerCase());
    addedCount++;
  }
}

console.log(`Added ${addedCount} new words. Total: ${existingWords.length}`);

// Truncate to exactly 1000 if we have more
if (existingWords.length > 1000) {
  existingWords.length = 1000;
  console.log(`Truncated to 1000 words`);
}

// Save updated words
writeFileSync(dataPath, JSON.stringify(existingWords, null, 2));
console.log('Words file updated successfully!');

