import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = resolve(__dirname, '../src/data');

if (!existsSync(dataDir)) {
  mkdirSync(dataDir, { recursive: true });
}

// Curated words with definitions
const words = [
  { word: "susurrus", pos: "noun", definition: "A whispering or rustling sound", examples: ["The susurrus of wind through autumn leaves filled the garden.", "She fell asleep to the gentle susurrus of the nearby stream."] },
  { word: "petrichor", pos: "noun", definition: "The pleasant earthy smell after rain", examples: ["After the summer storm, the petrichor rose from the warm pavement.", "Nothing beats the petrichor of a garden after a light drizzle."] },
  { word: "ephemeral", pos: "adjective", definition: "Lasting for a very short time", examples: ["The ephemeral beauty of cherry blossoms draws crowds each spring.", "Fame can be ephemeral in the age of social media."] },
  { word: "mellifluous", pos: "adjective", definition: "Sweet or musical; pleasant to hear", examples: ["Her mellifluous voice captivated the entire audience.", "The mellifluous tones of the cello filled the concert hall."] },
  { word: "serendipity", pos: "noun", definition: "The occurrence of events by chance in a happy way", examples: ["Finding that rare book was pure serendipity.", "Their meeting was a moment of serendipity that changed both their lives."] },
  { word: "luminescent", pos: "adjective", definition: "Emitting light not caused by heat", examples: ["The luminescent plankton made the waves glow blue at night.", "Her luminescent skin seemed to glow in the moonlight."] },
  { word: "ethereal", pos: "adjective", definition: "Extremely delicate and light; heavenly", examples: ["The dancer moved with ethereal grace across the stage.", "Morning mist gave the forest an ethereal quality."] },
  { word: "sonder", pos: "noun", definition: "The realization that each passerby has a life as vivid as your own", examples: ["Standing in the busy station, she felt a profound sense of sonder.", "The concept of sonder reminds us of our shared humanity."] },
  { word: "halcyon", pos: "adjective", definition: "Denoting a period of time that was idyllically happy and peaceful", examples: ["She often reminisced about halcyon summer days of her youth.", "The halcyon years before the war seemed like a distant dream."] },
  { word: "ineffable", pos: "adjective", definition: "Too great or extreme to be expressed in words", examples: ["The ineffable beauty of the aurora left them speechless.", "There was an ineffable sadness in his eyes."] },
  { word: "vellichor", pos: "noun", definition: "The strange wistfulness of used bookstores", examples: ["She wandered the aisles, overcome by vellichor.", "The vellichor of the old shop transported him to another era."] },
  { word: "apricity", pos: "noun", definition: "The warmth of the sun in winter", examples: ["They sat on the bench enjoying the apricity.", "The cat stretched out in a patch of apricity."] },
  { word: "limerence", pos: "noun", definition: "The state of being infatuated with another person", examples: ["His limerence made it impossible to concentrate on work.", "The early stages of limerence can feel overwhelming."] },
  { word: "querencia", pos: "noun", definition: "A place where one feels safe and at home", examples: ["The library had always been her querencia.", "Everyone needs a querencia to retreat to."] },
  { word: "phosphenes", pos: "noun", definition: "The light patterns seen when you close your eyes", examples: ["Pressing her palms to her eyes, she watched the phosphenes dance.", "The phosphenes swirled in kaleidoscopic patterns."] },
  { word: "fernweh", pos: "noun", definition: "A longing for distant places; the opposite of homesickness", examples: ["Looking at travel photos filled her with fernweh.", "His fernweh drove him to explore remote corners of the world."] },
  { word: "eudaimonia", pos: "noun", definition: "A state of happiness and well-being", examples: ["The philosopher argued that eudaimonia comes from virtue.", "She finally achieved a sense of eudaimonia in her life."] },
  { word: "sillage", pos: "noun", definition: "The trail of scent left behind by someone", examples: ["Her sillage of jasmine lingered in the hallway.", "He recognized her sillage before he saw her."] },
  { word: "komorebi", pos: "noun", definition: "Sunlight filtering through leaves", examples: ["The komorebi created dancing patterns on the forest floor.", "They picnicked in the gentle komorebi."] },
  { word: "hiraeth", pos: "noun", definition: "A deep longing for home or a place that no longer exists", examples: ["The old song filled him with hiraeth.", "Immigrants often experience a profound hiraeth."] },
  { word: "sonorous", pos: "adjective", definition: "Capable of producing a deep, rich sound", examples: ["His sonorous voice commanded attention.", "The sonorous bells echoed through the valley."] },
  { word: "dulcet", pos: "adjective", definition: "Sweet and soothing, especially of sound", examples: ["The dulcet tones of the flute calmed the child.", "She spoke in dulcet whispers."] },
  { word: "effervescent", pos: "adjective", definition: "Vivacious and enthusiastic", examples: ["Her effervescent personality lit up the room.", "The effervescent champagne bubbled in the glass."] },
  { word: "resplendent", pos: "adjective", definition: "Impressive through being richly colorful or sumptuous", examples: ["The bride looked resplendent in her gown.", "The resplendent sunset painted the sky orange."] },
  { word: "incandescent", pos: "adjective", definition: "Emitting light as a result of being heated; passionate", examples: ["The incandescent bulb cast a warm glow.", "Her incandescent rage was terrifying to witness."] },
  { word: "gossamer", pos: "adjective", definition: "Very light, thin, and insubstantial", examples: ["Gossamer curtains fluttered in the breeze.", "The gossamer wings of the dragonfly caught the light."] },
  { word: "eloquent", pos: "adjective", definition: "Fluent or persuasive in speaking or writing", examples: ["The lawyer made an eloquent argument.", "Her eloquent letter moved him to tears."] },
  { word: "redolent", pos: "adjective", definition: "Strongly reminiscent or suggestive of", examples: ["The kitchen was redolent of fresh bread.", "The scene was redolent of his childhood."] },
  { word: "quiescent", pos: "adjective", definition: "In a state of quietness or inactivity", examples: ["The volcano had been quiescent for centuries.", "The quiescent afternoon passed peacefully."] },
  { word: "iridescent", pos: "adjective", definition: "Showing luminous colors that change with angle", examples: ["The iridescent soap bubble floated away.", "The beetle had iridescent wings."] },
  { word: "effulgent", pos: "adjective", definition: "Shining brightly; radiant", examples: ["The effulgent moon lit the path.", "Her effulgent smile warmed everyone."] },
  { word: "verdant", pos: "adjective", definition: "Green with grass or rich vegetation", examples: ["The verdant hills rolled into the distance.", "Spring rains made the meadow verdant."] },
  { word: "ebullient", pos: "adjective", definition: "Cheerful and full of energy", examples: ["The ebullient crowd cheered wildly.", "Her ebullient nature was infectious."] },
  { word: "bucolic", pos: "adjective", definition: "Relating to pleasant countryside scenery", examples: ["They escaped to a bucolic village.", "The painting depicted a bucolic landscape."] },
  { word: "sempiternal", pos: "adjective", definition: "Eternal and unchanging; everlasting", examples: ["The stars seemed sempiternal in their courses.", "Their sempiternal bond transcended time."] },
  { word: "sanguine", pos: "adjective", definition: "Optimistic or positive, especially in difficult situations", examples: ["She remained sanguine about the outcome.", "His sanguine disposition helped him through."] },
  { word: "limpid", pos: "adjective", definition: "Free of anything that darkens; clear", examples: ["The limpid stream revealed every pebble.", "Her limpid eyes held no secrets."] },
  { word: "pellucid", pos: "adjective", definition: "Translucently clear; easily understood", examples: ["The pellucid water invited swimmers.", "His pellucid writing style was admired."] },
  { word: "lambent", pos: "adjective", definition: "Softly bright or radiant", examples: ["Lambent flames flickered in the fireplace.", "Her lambent wit charmed everyone."] },
  { word: "numinous", pos: "adjective", definition: "Having a strong spiritual quality", examples: ["The cathedral had a numinous atmosphere.", "She felt numinous presence in the grove."] },
  { word: "crepuscular", pos: "adjective", definition: "Of or resembling twilight", examples: ["Deer are crepuscular creatures.", "The crepuscular light softened the landscape."] },
  { word: "diaphanous", pos: "adjective", definition: "Light, delicate, and translucent", examples: ["She wore a diaphanous gown.", "Diaphanous curtains let in the light."] },
  { word: "lissome", pos: "adjective", definition: "Thin, supple, and graceful", examples: ["The lissome dancer leaped effortlessly.", "Her lissome figure moved through the crowd."] },
  { word: "lithe", pos: "adjective", definition: "Thin, supple, and graceful", examples: ["The lithe gymnast performed flawlessly.", "Cats are known for their lithe movements."] },
  { word: "scintillating", pos: "adjective", definition: "Sparkling or shining brightly; brilliant", examples: ["The scintillating diamonds caught every eye.", "She gave a scintillating performance."] },
  { word: "aureate", pos: "adjective", definition: "Made of or having the color of gold", examples: ["The aureate sunset was breathtaking.", "His aureate prose style was distinctive."] },
  { word: "cerulean", pos: "adjective", definition: "Deep sky blue in color", examples: ["The cerulean sea stretched to the horizon.", "She painted the ceiling cerulean."] },
  { word: "viridian", pos: "adjective", definition: "A bluish-green color", examples: ["The viridian forest beckoned hikers.", "She chose viridian for the accent wall."] },
  { word: "vermillion", pos: "noun", definition: "A brilliant red pigment or color", examples: ["The vermillion leaves signaled autumn.", "Artists prized vermillion for its intensity."] },
  { word: "alabaster", pos: "adjective", definition: "White and smooth like alabaster stone", examples: ["Her alabaster skin glowed in the candlelight.", "The alabaster columns framed the entrance."] }
];

// Additional word templates to expand to 1000
const moreWords = [
  { word: "susurrant", pos: "adjective", definition: "Whispering or rustling", examples: ["The susurrant leaves created a peaceful backdrop.", "Her susurrant voice was barely audible."] },
  { word: "pulchritude", pos: "noun", definition: "Physical beauty", examples: ["The garden's pulchritude attracted many visitors.", "Her pulchritude was legendary."] },
  { word: "elysian", pos: "adjective", definition: "Beautiful or creative; divinely inspired", examples: ["They spent elysian days by the shore.", "The elysian fields beckoned."] },
  { word: "beguile", pos: "verb", definition: "To charm or enchant, often deceptively", examples: ["The magician sought to beguile the audience.", "Her stories beguiled all who listened."] },
  { word: "plethora", pos: "noun", definition: "An excess or overabundance", examples: ["A plethora of options made choosing difficult.", "The garden offered a plethora of colors."] },
  { word: "ephemera", pos: "noun", definition: "Things that exist for only a short time", examples: ["She collected vintage ephemera.", "Social media posts are modern ephemera."] },
  { word: "somnolent", pos: "adjective", definition: "Sleepy or drowsy", examples: ["The somnolent cat dozed on the windowsill.", "The warm afternoon made everyone somnolent."] },
  { word: "melancholy", pos: "noun", definition: "A deep, pensive sadness", examples: ["Autumn brings a certain melancholy.", "The music evoked a sweet melancholy."] },
  { word: "wistful", pos: "adjective", definition: "Having a feeling of vague or regretful longing", examples: ["She gave a wistful sigh.", "His wistful gaze followed the departing train."] },
  { word: "languorous", pos: "adjective", definition: "Characterized by tiredness or inactivity", examples: ["They spent languorous afternoons reading.", "The languorous heat slowed everything down."] },
  { word: "aureole", pos: "noun", definition: "A circle of light around the head; a halo", examples: ["The saint was depicted with an aureole.", "The setting sun created an aureole."] },
  { word: "coruscate", pos: "verb", definition: "To flash or sparkle", examples: ["Diamonds coruscate in the light.", "Her wit coruscated throughout the evening."] },
  { word: "nacreous", pos: "adjective", definition: "Having the iridescent quality of mother-of-pearl", examples: ["The nacreous shell caught the light.", "Nacreous clouds appeared at dawn."] },
  { word: "opalescent", pos: "adjective", definition: "Showing varying colors like an opal", examples: ["The opalescent vase was her favorite.", "Morning mist gave the lake an opalescent quality."] },
  { word: "plangent", pos: "adjective", definition: "Having a loud reverberating sound, often mournful", examples: ["The plangent church bells echoed.", "Her plangent cry pierced the silence."] },
  { word: "dulcimer", pos: "noun", definition: "A musical stringed instrument", examples: ["She played the dulcimer beautifully.", "The dulcimer's tones filled the hall."] },
  { word: "zephyr", pos: "noun", definition: "A soft gentle breeze", examples: ["A zephyr rustled the curtains.", "The zephyr carried the scent of flowers."] },
  { word: "palimpsest", pos: "noun", definition: "Something reused but bearing traces of earlier use", examples: ["The city was a palimpsest of styles.", "Her face was a palimpsest of emotions."] },
  { word: "reverie", pos: "noun", definition: "A state of being pleasantly lost in thought", examples: ["She was lost in a reverie.", "The music inspired a peaceful reverie."] },
  { word: "solace", pos: "noun", definition: "Comfort in a time of distress", examples: ["She found solace in music.", "Books offered solace during hard times."] },
  { word: "respite", pos: "noun", definition: "A short period of rest from something difficult", examples: ["The vacation offered respite from work.", "Rain provided respite from the heat."] },
  { word: "tranquil", pos: "adjective", definition: "Free from disturbance; calm", examples: ["The tranquil lake reflected the mountains.", "She led a tranquil life."] },
  { word: "serene", pos: "adjective", definition: "Calm, peaceful, and untroubled", examples: ["Her serene expression calmed others.", "The serene landscape inspired artists."] },
  { word: "placid", pos: "adjective", definition: "Not easily upset or excited; calm", examples: ["The placid waters mirrored the sky.", "His placid temperament was reassuring."] },
  { word: "demure", pos: "adjective", definition: "Reserved, modest, and shy", examples: ["She gave a demure smile.", "His demure manner belied his ambition."] },
  { word: "winsome", pos: "adjective", definition: "Attractive or appealing in appearance", examples: ["The winsome child charmed everyone.", "Her winsome ways won many friends."] },
  { word: "blithe", pos: "adjective", definition: "Showing a casual and cheerful indifference", examples: ["He maintained a blithe attitude.", "Her blithe spirit was infectious."] },
  { word: "felicity", pos: "noun", definition: "Intense happiness; the ability to find apt expression", examples: ["The wedding was a day of felicity.", "He wrote with great felicity."] },
  { word: "beatitude", pos: "noun", definition: "Supreme blessedness or happiness", examples: ["Her face showed pure beatitude.", "The monks sought beatitude through prayer."] },
  { word: "bliss", pos: "noun", definition: "Perfect happiness; great joy", examples: ["Ignorance is bliss, they say.", "The couple lived in wedded bliss."] },
  { word: "rapture", pos: "noun", definition: "A feeling of intense pleasure or joy", examples: ["She listened in rapture.", "The sunset filled him with rapture."] },
  { word: "elation", pos: "noun", definition: "Great happiness and exhilaration", examples: ["Elation spread through the crowd.", "Her elation was palpable."] },
  { word: "jubilation", pos: "noun", definition: "A feeling of great happiness and triumph", examples: ["Jubilation erupted when they won.", "The streets filled with jubilation."] },
  { word: "exuberance", pos: "noun", definition: "The quality of being full of energy and excitement", examples: ["Her exuberance was contagious.", "Spring brings exuberance to nature."] },
  { word: "vivacity", pos: "noun", definition: "The quality of being attractively lively", examples: ["Her vivacity charmed everyone.", "The party had great vivacity."] },
  { word: "effervescence", pos: "noun", definition: "Bubbles in a liquid; vivacity and enthusiasm", examples: ["The champagne's effervescence tickled her nose.", "His effervescence lifted spirits."] },
  { word: "ebullience", pos: "noun", definition: "The quality of being cheerful and energetic", examples: ["Her ebullience was hard to ignore.", "The team's ebullience was infectious."] },
  { word: "exhilaration", pos: "noun", definition: "A feeling of excitement and happiness", examples: ["The ride filled her with exhilaration.", "Victory brought exhilaration."] },
  { word: "euphoria", pos: "noun", definition: "A feeling of intense excitement and happiness", examples: ["Euphoria swept through the stadium.", "The news brought a sense of euphoria."] },
  { word: "rhapsody", pos: "noun", definition: "An effusively enthusiastic expression of feeling", examples: ["She went into rhapsodies about the food.", "The symphony's rhapsody moved audiences."] },
  { word: "idyll", pos: "noun", definition: "An extremely happy or peaceful period", examples: ["Their summer romance was an idyll.", "The pastoral idyll seemed timeless."] },
  { word: "arcadia", pos: "noun", definition: "An idealized place of rural peace", examples: ["They sought their own arcadia.", "The valley was their private arcadia."] },
  { word: "haven", pos: "noun", definition: "A place of safety or refuge", examples: ["The cottage was their haven.", "She found a haven from the storm."] },
  { word: "sanctuary", pos: "noun", definition: "A place of refuge or safety", examples: ["The garden was her sanctuary.", "Birds found sanctuary in the preserve."] },
  { word: "bower", pos: "noun", definition: "A pleasant shady place under trees", examples: ["They rested in a leafy bower.", "The bower offered cool shade."] },
  { word: "arbor", pos: "noun", definition: "A shady garden alcove with climbing plants", examples: ["Roses covered the arbor.", "They married under the arbor."] },
  { word: "glade", pos: "noun", definition: "An open space in a forest", examples: ["Sunlight filled the glade.", "Deer grazed in the glade."] },
  { word: "dell", pos: "noun", definition: "A small valley, usually wooded", examples: ["A stream ran through the dell.", "The dell was carpeted with wildflowers."] },
  { word: "copse", pos: "noun", definition: "A small group of trees", examples: ["A copse of birches stood nearby.", "The copse provided shelter from wind."] },
  { word: "thicket", pos: "noun", definition: "A dense group of bushes or trees", examples: ["Rabbits hid in the thicket.", "The path wound through a thicket."] }
];

// More words to reach 1000
const additionalWords = [
  ["sylvan", "adjective", "Relating to or characteristic of woods", "The sylvan setting was perfect for meditation.", "Sylvan creatures emerged at dusk."],
  ["arboreal", "adjective", "Relating to or living in trees", "Monkeys are arboreal creatures.", "The arboreal canopy blocked the sun."],
  ["riparian", "adjective", "Relating to the banks of a river", "Riparian vegetation lined the stream.", "The riparian zone supported diverse wildlife."],
  ["littoral", "adjective", "Relating to the shore of a sea or lake", "Littoral ecosystems are delicate.", "The littoral zone teemed with life."],
  ["telluric", "adjective", "Relating to the earth", "Telluric forces shaped the mountains.", "The telluric vibrations were recorded."],
  ["celestial", "adjective", "Relating to the sky or heavens", "Celestial bodies filled the night sky.", "The celestial music enchanted all."],
  ["astral", "adjective", "Relating to or resembling stars", "Astral projections fascinated her.", "The astral plane called to him."],
  ["stellar", "adjective", "Relating to stars; exceptionally good", "Stellar performances earned applause.", "The stellar display amazed astronomers."],
  ["nebulous", "adjective", "Hazy, vague, or ill-defined", "His plans were nebulous at best.", "Nebulous clouds drifted overhead."],
  ["liminal", "adjective", "Relating to a transitional stage", "Dawn is a liminal time.", "The liminal space felt magical."],
  ["penumbral", "adjective", "Relating to partial shadow", "Penumbral light softened the room.", "The penumbral eclipse began at noon."],
  ["umbral", "adjective", "Relating to shadow", "Umbral regions cooled quickly.", "The umbral zone was in darkness."],
  ["tenebrous", "adjective", "Dark, shadowy, or obscure", "The tenebrous cave inspired fear.", "Tenebrous thoughts clouded his mind."],
  ["caliginous", "adjective", "Misty, dark, or obscure", "The caliginous morning hid the sun.", "Caliginous depths of the ocean await."],
  ["murky", "adjective", "Dark and gloomy; not clear", "The murky water hid dangers.", "His murky past remained a mystery."],
  ["lustrous", "adjective", "Having a gentle sheen or glow", "Her lustrous hair caught the light.", "The lustrous pearl was priceless."],
  ["burnished", "adjective", "Polished and made shiny by rubbing", "The burnished armor gleamed.", "Burnished copper adorned the door."],
  ["patina", "noun", "A sheen produced by age on surfaces", "The bronze had a green patina.", "Time gave the furniture patina."],
  ["verdigris", "noun", "Bright green coating on copper or brass", "Verdigris covered the old statue.", "The verdigris showed the bell's age."],
  ["tarnish", "noun", "Loss of luster; a dull film on metal", "Silver develops tarnish over time.", "Nothing could tarnish her reputation."],
  ["sheen", "noun", "A soft luster on a surface", "The fabric had a silky sheen.", "Morning dew gave the grass sheen."],
  ["gloss", "noun", "A shine or luster on a surface", "The car had a high gloss finish.", "Lip gloss made her lips shimmer."],
  ["luster", "noun", "A gentle sheen or soft glow", "Pearls are prized for their luster.", "Her eyes had lost their luster."],
  ["gleam", "noun", "A faint or brief light or shine", "A gleam of hope appeared.", "The gleam of gold caught his eye."],
  ["glimmer", "noun", "A faint unsteady light", "A glimmer of light showed the way.", "She saw a glimmer of understanding."],
  ["shimmer", "noun", "A soft trembling light", "The shimmer on the lake was lovely.", "Heat caused a shimmer on the road."],
  ["twinkle", "noun", "A sparkle or gleam in the eyes", "His eyes had a mischievous twinkle.", "Stars twinkle in the night sky."],
  ["sparkle", "noun", "A glittering flash of light", "The diamond's sparkle was brilliant.", "Her personality had real sparkle."],
  ["glitter", "noun", "A sparkling light or brilliance", "The glitter of gold attracted miners.", "Glitter covered the party decorations."],
  ["radiance", "noun", "Light or heat emanating from something", "The radiance of the sun warmed them.", "Her radiance lit up the room."],
  ["brilliance", "noun", "Intense brightness of light", "The diamond's brilliance was stunning.", "His brilliance as a scholar was known."],
  ["luminosity", "noun", "The quality of emitting light", "The luminosity of the full moon guided them.", "Her luminosity on stage was captivating."],
  ["incandescence", "noun", "Light produced by high temperature", "The incandescence of the filament provided light.", "His incandescence on stage was remarkable."],
  ["phosphorescence", "noun", "Light emitted without heat", "The phosphorescence of the waves amazed them.", "Phosphorescence made the path visible."],
  ["bioluminescence", "noun", "Light produced by living organisms", "Bioluminescence in the bay was magical.", "Deep sea creatures use bioluminescence."],
  ["fluorescence", "noun", "Visible light from absorption of radiation", "The mineral showed bright fluorescence.", "Fluorescence revealed the hidden writing."],
  ["aurora", "noun", "A natural light display in the sky", "The aurora borealis danced overhead.", "They traveled north to see the aurora."],
  ["twilight", "noun", "Soft glowing light from the sky after sunset", "They walked home in the twilight.", "Twilight colors painted the clouds."],
  ["dusk", "noun", "The darker stage of twilight", "Fireflies appeared at dusk.", "They arrived home at dusk."],
  ["gloaming", "noun", "Twilight or dusk", "Owls emerge in the gloaming.", "The gloaming gave the hills a purple tint."],
  ["eventide", "noun", "The end of day; evening", "Peace descends at eventide.", "They met at eventide by the lake."],
  ["vesper", "noun", "Evening; relating to evening", "Vesper bells rang across the valley.", "The vesper hour brought calm."],
  ["nocturne", "noun", "A musical composition inspired by night", "Chopin's nocturnes are beautiful.", "She composed a nocturne for piano."],
  ["serenade", "noun", "A piece of music sung outdoors at night", "He played a serenade beneath her window.", "The serenade echoed through the streets."],
  ["lullaby", "noun", "A quiet song to send a child to sleep", "She sang a gentle lullaby.", "The lullaby calmed the restless baby."],
  ["requiem", "noun", "A Mass for the repose of souls; music for this", "Mozart's requiem is a masterpiece.", "They played a requiem for the departed."],
  ["elegy", "noun", "A poem of serious reflection, typically a lament", "He wrote an elegy for his friend.", "The elegy moved many to tears."],
  ["ode", "noun", "A type of lyrical poem", "She composed an ode to spring.", "Keats wrote his famous ode to a nightingale."],
  ["sonnet", "noun", "A poem of fourteen lines", "Shakespeare wrote many sonnets.", "The sonnet expressed his love perfectly."],
  ["ballad", "noun", "A poem or song narrating a story", "The ballad told of ancient battles.", "She sang a traditional ballad."],
  ["aria", "noun", "A long accompanied song for solo voice", "The soprano's aria was stunning.", "The opera featured a famous aria."],
  ["cadence", "noun", "A modulation in the voice; rhythmic flow", "The cadence of his speech was soothing.", "Poetry has a natural cadence."],
  ["timbre", "noun", "The character of a musical sound", "The violin has a warm timbre.", "Her voice had a unique timbre."],
  ["resonance", "noun", "The quality of being resonant", "The hall had excellent resonance.", "His words had deep resonance."],
  ["harmony", "noun", "The combination of musical notes; agreement", "The choir sang in harmony.", "They lived in harmony with nature."],
  ["melody", "noun", "A sequence of notes forming a tune", "The melody was instantly memorable.", "Birds sang their morning melodies."],
  ["symphony", "noun", "An elaborate musical composition", "Beethoven's symphonies are legendary.", "The symphony of colors amazed visitors."],
  ["crescendo", "noun", "A gradual increase in loudness", "The music built to a crescendo.", "His speech reached a crescendo."],
  ["diminuendo", "noun", "A gradual decrease in loudness", "The piece ended in a gentle diminuendo.", "The diminuendo was beautifully executed."],
  ["pianissimo", "adjective", "Very soft in music", "The pianissimo passage was delicate.", "She played the notes pianissimo."],
  ["fortissimo", "adjective", "Very loud in music", "The fortissimo section was powerful.", "The orchestra played fortissimo."],
  ["legato", "adjective", "In a smooth flowing manner", "Play this passage legato.", "The legato phrasing was lovely."],
  ["staccato", "adjective", "With each note sharply detached", "The staccato notes punctuated the melody.", "Her staccato speech revealed her anger."],
  ["rubato", "noun", "Temporary disregard of strict tempo", "The pianist used rubato expressively.", "Rubato gives music emotional depth."],
  ["virtuoso", "noun", "A person highly skilled in music or art", "The virtuoso amazed the audience.", "She was a virtuoso on the violin."],
  ["maestro", "noun", "A distinguished conductor or musician", "The maestro took his bow.", "He studied under a famous maestro."],
  ["muse", "noun", "A source of inspiration", "Nature was his muse.", "The artist found his muse in travel."],
  ["reverie", "noun", "A state of being pleasantly lost in thought", "She fell into a daydream reverie.", "The music induced a gentle reverie."],
  ["whimsy", "noun", "Playfully quaint or fanciful behavior", "The garden was full of whimsy.", "Her whimsy delighted children."],
  ["caprice", "noun", "A sudden change of mood or behavior", "Her caprices kept them guessing.", "The weather's caprice ruined plans."],
  ["fancy", "noun", "A superficial liking; imagination", "It was just a passing fancy.", "Let your fancy guide you."],
  ["vagary", "noun", "An unpredictable change or action", "The vagaries of fate intervened.", "Weather vagaries affected the harvest."],
  ["vicissitude", "noun", "A change of circumstances, typically unwelcome", "Life's vicissitudes test us all.", "They weathered many vicissitudes."],
  ["flux", "noun", "Continuous change or movement", "Everything is in a state of flux.", "The flux of the tides amazed her."],
  ["metamorphosis", "noun", "A change of form or nature", "The butterfly's metamorphosis is remarkable.", "He underwent a complete metamorphosis."],
  ["transformation", "noun", "A thorough or dramatic change", "The transformation was astonishing.", "Her transformation inspired others."],
  ["transfiguration", "noun", "A complete change of form or appearance", "The transfiguration was miraculous.", "Art can cause transfiguration."],
  ["transmutation", "noun", "The action of changing form or nature", "Alchemists sought transmutation of metals.", "His transmutation was gradual."],
  ["alchemy", "noun", "A seemingly magical process of transformation", "There was alchemy in their partnership.", "The alchemy of cooking fascinated her."],
  ["enigma", "noun", "Something mysterious or difficult to understand", "She remained an enigma to all.", "The ancient text was an enigma."],
  ["conundrum", "noun", "A confusing and difficult problem", "The situation posed a conundrum.", "Life presents many conundrums."],
  ["paradox", "noun", "A seemingly contradictory statement", "The grandfather paradox puzzles many.", "His life was a paradox."],
  ["quandary", "noun", "A state of perplexity or uncertainty", "She was in a quandary about what to do.", "The ethical quandary troubled him."],
  ["labyrinth", "noun", "A complicated network of passages", "The garden maze was a labyrinth.", "Her mind was a labyrinth of thoughts."],
  ["meander", "verb", "To follow a winding course", "The river meanders through the valley.", "They meandered through the market."],
  ["amble", "verb", "To walk at a slow, relaxed pace", "They ambled along the beach.", "He ambled through the park daily."],
  ["saunter", "verb", "To walk in a slow, relaxed manner", "She sauntered into the room.", "They sauntered down the avenue."],
  ["stroll", "verb", "To walk in a leisurely way", "They strolled through the gardens.", "An evening stroll helps relaxation."],
  ["wander", "verb", "To walk or move in a leisurely way", "She loved to wander through old towns.", "His thoughts began to wander."],
  ["roam", "verb", "To move about without a fixed destination", "Deer roam the forest freely.", "He roamed the world for years."],
  ["ramble", "verb", "To walk for pleasure in the countryside", "They rambled through the hills.", "His speech began to ramble."],
  ["gallivant", "verb", "To go around from place to place seeking pleasure", "She gallivanted around Europe.", "They spent summers gallivanting."],
  ["traipse", "verb", "To walk or move wearily or reluctantly", "She traipsed around the shops all day.", "He traipsed through the mud."],
  ["perambulate", "verb", "To walk or travel through", "Families perambulated in the park.", "The professor perambulated the campus."],
  ["sojourn", "noun", "A temporary stay", "Their sojourn in Paris was memorable.", "She made a brief sojourn in Rome."],
  ["odyssey", "noun", "A long and eventful journey", "The trip became an odyssey.", "His career was quite an odyssey."],
  ["voyage", "noun", "A long journey, especially by sea or space", "The voyage lasted three months.", "They embarked on a voyage of discovery."],
  ["pilgrimage", "noun", "A journey to a sacred place", "The pilgrimage changed her life.", "Millions make the pilgrimage yearly."],
  ["expedition", "noun", "A journey undertaken for a specific purpose", "The expedition to Antarctica succeeded.", "They organized an expedition to find it."],
  ["excursion", "noun", "A short journey made for pleasure", "The weekend excursion was delightful.", "They planned an excursion to the coast."],
  ["jaunt", "noun", "A short trip taken for pleasure", "A jaunt to the countryside refreshed them.", "The jaunt lifted everyone's spirits."],
  ["escapade", "noun", "An act involving excitement or adventure", "Their escapade made headlines.", "Youthful escapades are fondly remembered."]
];

// Even more words to continue filling the list
const moreWords2 = [
  ["folderol", "noun", "Trivial or nonsensical fuss", "Enough of this folderol.", "The folderol distracted from real issues."],
  ["kerfuffle", "noun", "A commotion or fuss", "The announcement caused a kerfuffle.", "The kerfuffle died down quickly."],
  ["brouhaha", "noun", "A noisy and overexcited reaction", "The brouhaha over the decision was intense.", "What's all this brouhaha about?"],
  ["hubbub", "noun", "A loud and chaotic noise", "The hubbub of the crowd was deafening.", "Amid the hubbub, she stayed calm."],
  ["hullabaloo", "noun", "A commotion or fuss", "The hullabaloo attracted attention.", "What's all the hullabaloo?"],
  ["tumult", "noun", "A loud confused noise; commotion", "The tumult of the crowd overwhelmed him.", "Tumult broke out in the streets."],
  ["clamor", "noun", "A loud and confused noise", "The clamor of the market was vibrant.", "Public clamor forced a response."],
  ["din", "noun", "A loud, unpleasant noise", "The din of construction was constant.", "They could barely hear over the din."],
  ["cacophony", "noun", "A harsh discordant mixture of sounds", "The cacophony of horns filled the air.", "Rush hour creates a cacophony."],
  ["dissonance", "noun", "Lack of harmony; disagreement", "Musical dissonance creates tension.", "There was dissonance in the group."],
  ["discordance", "noun", "Disagreement or lack of harmony", "The discordance of their views was evident.", "Musical discordance can be intentional."],
  ["concordance", "noun", "Agreement or consistency", "The concordance of evidence was compelling.", "They reached concordance on the issue."],
  ["consonance", "noun", "Agreement or harmony", "The consonance of their views helped.", "Musical consonance creates resolution."],
  ["euphony", "noun", "Pleasant sound especially in words", "The euphony of the poem was beautiful.", "Writers strive for euphony."],
  ["mellifluence", "noun", "Sweet smooth flow of sound", "The mellifluence of her voice charmed all.", "The song's mellifluence was soothing."],
  ["assonance", "noun", "Resemblance of sounds between syllables", "Poets use assonance for effect.", "The assonance created a musical quality."],
  ["alliteration", "noun", "Occurrence of the same letter or sound", "Peter Piper is classic alliteration.", "Alliteration makes phrases memorable."],
  ["onomatopoeia", "noun", "Formation of words from sounds", "Buzz is an example of onomatopoeia.", "Onomatopoeia enlivens writing."],
  ["synesthesia", "noun", "Production of a sense in one modality by another", "She experienced synesthesia with music.", "Synesthesia lets some see sounds."],
  ["phantasmagoria", "noun", "A sequence of dreamlike imagery", "The film was a phantasmagoria of color.", "Fever dreams are often phantasmagorias."],
  ["chimera", "noun", "A thing hoped for but illusory", "The plan was a mere chimera.", "He chased chimeras all his life."],
  ["mirage", "noun", "An optical illusion; something illusory", "The oasis was a mirage.", "Success seemed like a mirage."],
  ["apparition", "noun", "A ghost or ghostly figure", "An apparition appeared at midnight.", "The apparition vanished quickly."],
  ["specter", "noun", "A ghost; something widely feared", "The specter of war loomed.", "A specter haunted the old mansion."],
  ["phantasm", "noun", "A figment of imagination; illusion", "Was it real or a phantasm?", "Phantasms filled his troubled dreams."],
  ["revenant", "noun", "A person who has returned from the dead", "The legend spoke of a revenant.", "The revenant sought vengeance."],
  ["wraith", "noun", "A ghost or ghostly image", "A wraith drifted through the hall.", "She looked like a pale wraith."],
  ["eidolon", "noun", "An idealized person or thing; specter", "She was the eidolon of grace.", "The eidolon appeared at twilight."],
  ["avatar", "noun", "An incarnation or embodiment", "She was the avatar of elegance.", "The avatar represented the deity."],
  ["incarnation", "noun", "A person who embodies a quality", "He was the incarnation of evil.", "This was his finest incarnation."],
  ["manifestation", "noun", "A display or demonstration", "The storm was a manifestation of nature's power.", "This was a manifestation of change."],
  ["epiphany", "noun", "A moment of sudden revelation", "She had an epiphany about her life.", "The epiphany changed everything."],
  ["revelation", "noun", "A surprising and previously unknown fact", "The revelation shocked everyone.", "It came as a startling revelation."],
  ["illumination", "noun", "Lighting; clarification of understanding", "The illumination revealed the painting's details.", "Sudden illumination struck him."],
  ["enlightenment", "noun", "The state of gaining knowledge", "She sought spiritual enlightenment.", "The age of enlightenment transformed society."],
  ["wisdom", "noun", "The quality of having experience and knowledge", "Wisdom comes with age.", "Her wisdom guided the community."],
  ["sagacity", "noun", "The quality of being wise", "His sagacity was legendary.", "Sagacity is valued in leaders."],
  ["prudence", "noun", "Acting with care for the future", "Prudence guided her investments.", "Financial prudence is important."],
  ["discernment", "noun", "The ability to judge well", "She showed great discernment.", "Discernment is a valuable skill."],
  ["acumen", "noun", "The ability to make good judgments", "Her business acumen was impressive.", "Political acumen served him well."],
  ["perspicacity", "noun", "The quality of keen mental perception", "His perspicacity solved the mystery.", "Perspicacity is rare and valuable."],
  ["prescience", "noun", "Knowledge of events before they happen", "Her prescience about the market amazed everyone.", "It seemed like prescience."],
  ["clairvoyance", "noun", "The ability to perceive beyond normal senses", "She claimed to have clairvoyance.", "His clairvoyance about trends was uncanny."],
  ["intuition", "noun", "Understanding without conscious reasoning", "She trusted her intuition.", "Intuition guided his decisions."],
  ["instinct", "noun", "An innate pattern of behavior", "Instinct told her to run.", "Trust your instincts sometimes."],
  ["premonition", "noun", "A strong feeling about a future event", "She had a premonition of danger.", "The premonition proved accurate."],
  ["foreboding", "noun", "A feeling that something bad will happen", "A sense of foreboding filled her.", "Foreboding hung in the air."],
  ["presentiment", "noun", "An intuitive feeling about the future", "A presentiment of trouble arose.", "He couldn't shake the presentiment."],
  ["harbinger", "noun", "Something that signals the approach of something", "The robin is a harbinger of spring.", "Dark clouds were harbingers of the storm."],
  ["portent", "noun", "A sign of something about to happen", "They saw it as a portent.", "The comet was viewed as a portent."],
  ["omen", "noun", "An event regarded as a sign of good or bad", "A black cat is considered an omen by some.", "They took it as a good omen."],
  ["augury", "noun", "A sign of what will happen; an omen", "The augury suggested success.", "Ancient augury involved bird observation."],
  ["auspice", "noun", "A divine or prophetic sign", "Under the auspices of the king, they set sail.", "The auspices were favorable."],
  ["talisman", "noun", "An object thought to have magic powers", "The talisman protected its wearer.", "She never traveled without her talisman."],
  ["amulet", "noun", "An ornament worn as protection against evil", "The amulet hung around his neck.", "Ancient cultures used amulets widely."],
  ["charm", "noun", "An object believed to have magical power", "The lucky charm brought her comfort.", "Charm bracelets were popular."],
  ["relic", "noun", "An object surviving from an earlier time", "The museum displayed ancient relics.", "The relic held religious significance."],
  ["artifact", "noun", "An object made by a human being", "The artifact was centuries old.", "Artifacts tell stories of the past."],
  ["heirloom", "noun", "A valuable object passed down through generations", "The ring was a family heirloom.", "Heirlooms connect us to ancestors."],
  ["keepsake", "noun", "A small item kept as a reminder", "She treasured the keepsake from her grandmother.", "They exchanged keepsakes."],
  ["memento", "noun", "An object kept as a reminder", "The photograph was a precious memento.", "Travelers collect mementos."],
  ["souvenir", "noun", "A thing kept as a reminder of a place", "She bought a souvenir from each city.", "Souvenirs filled her shelf."],
  ["remembrance", "noun", "The action of remembering; a memory", "In remembrance of those lost, they gathered.", "Sweet remembrances flooded back."],
  ["reminiscence", "noun", "An account of something remembered", "His reminiscences entertained everyone.", "Reminiscence brought smiles."],
  ["nostalgia", "noun", "A sentimental longing for the past", "The song filled her with nostalgia.", "Nostalgia for simpler times grew."],
  ["wistfulness", "noun", "A feeling of vague or regretful longing", "Wistfulness colored her memories.", "There was wistfulness in his voice."],
  ["yearning", "noun", "A feeling of intense longing", "A yearning for home overcame him.", "Her yearning for adventure was strong."],
  ["longing", "noun", "A persistent desire or craving", "Longing showed in her eyes.", "The longing for peace was universal."],
  ["craving", "noun", "A powerful desire for something", "Her craving for chocolate was intense.", "Cravings can be hard to resist."],
  ["hankering", "noun", "A strong desire to have or do something", "He had a hankering for adventure.", "A hankering for pie seized her."],
  ["yen", "noun", "A longing or yearning", "She had a yen for travel.", "His yen for knowledge was insatiable."],
  ["penchant", "noun", "A strong liking for something", "She had a penchant for drama.", "His penchant for sweets was known."],
  ["predilection", "noun", "A preference or special liking", "His predilection for jazz was evident.", "She had a predilection for vintage."],
  ["proclivity", "noun", "A tendency to choose something regularly", "His proclivity for risk worried them.", "Her proclivity for reading was strong."],
  ["propensity", "noun", "An inclination or tendency", "His propensity for lateness annoyed colleagues.", "She showed a propensity for kindness."],
  ["affinity", "noun", "A natural liking or sympathy", "She felt an affinity with the sea.", "Their affinity for each other was clear."],
  ["kinship", "noun", "A sharing of characteristics or origins", "They felt a kinship with fellow artists.", "Kinship bound the community together."],
  ["rapport", "noun", "A close and harmonious relationship", "They built a strong rapport.", "Good rapport makes teamwork easier."],
  ["camaraderie", "noun", "Mutual trust among people who spend time together", "Camaraderie developed among the team.", "The camaraderie was palpable."],
  ["fellowship", "noun", "Friendly association with others", "Fellowship enriched their lives.", "The fellowship met weekly."],
  ["amity", "noun", "Friendly relations between people or countries", "Amity between neighbors is valued.", "They lived in amity for decades."],
  ["cordiality", "noun", "Warm and friendly behavior", "His cordiality put guests at ease.", "Cordiality marked their interactions."],
  ["geniality", "noun", "Friendly and cheerful manner", "His geniality was well-known.", "Geniality made her popular."],
  ["affability", "noun", "Friendliness and ease of manner", "Her affability charmed everyone.", "Affability is an asset in business."],
  ["amiability", "noun", "Friendliness and pleasantness", "His amiability won many friends.", "Amiability smoothed many tensions."],
  ["benevolence", "noun", "The quality of being well-meaning", "Her benevolence touched many lives.", "Benevolence motivated his charity."],
  ["magnanimity", "noun", "Generosity toward a rival or less powerful person", "His magnanimity impressed even critics.", "Magnanimity is a noble quality."],
  ["munificence", "noun", "Great generosity", "The donor's munificence was celebrated.", "Munificence funded the new wing."],
  ["largesse", "noun", "Generosity in giving", "The king's largesse was legendary.", "Her largesse supported many causes."],
  ["philanthropy", "noun", "The desire to promote others' welfare", "Philanthropy was her life's work.", "Philanthropy can change communities."],
  ["altruism", "noun", "Selfless concern for others' well-being", "True altruism is rare.", "Altruism motivated her volunteer work."],
  ["selflessness", "noun", "Concern more with others than with oneself", "Her selflessness inspired many.", "Selflessness is a virtue."],
  ["magnanimous", "adjective", "Very generous or forgiving", "He was magnanimous in victory.", "Her magnanimous gesture surprised everyone."],
  ["benevolent", "adjective", "Well-meaning and kindly", "The benevolent ruler was loved.", "A benevolent smile crossed her face."],
  ["beneficent", "adjective", "Resulting in good; generous", "The beneficent policy helped many.", "Her beneficent nature was known."]
];

// Final batch of words
const moreWords3 = [
  ["clement", "adjective", "Mild or merciful", "The judge was clement in sentencing.", "Clement weather blessed the festival."],
  ["lenient", "adjective", "Permissive and not strict", "The teacher was lenient with deadlines.", "Lenient policies caused issues later."],
  ["indulgent", "adjective", "Readily giving in to wishes", "Grandparents are often indulgent.", "An indulgent smile showed her approval."],
  ["permissive", "adjective", "Allowing freedom of behavior", "The permissive culture shocked him.", "Permissive parenting has pros and cons."],
  ["tolerant", "adjective", "Showing willingness to accept differences", "A tolerant society values diversity.", "She was tolerant of mistakes."],
  ["forbearing", "adjective", "Patient and self-controlled", "He was forbearing despite provocations.", "Her forbearing nature calmed tensions."],
  ["stoic", "adjective", "Enduring pain without complaint", "He remained stoic through difficulties.", "Her stoic demeanor impressed everyone."],
  ["resilient", "adjective", "Able to recover quickly from difficulties", "Children are remarkably resilient.", "The resilient community rebuilt."],
  ["tenacious", "adjective", "Holding firmly to something", "Her tenacious spirit won the case.", "Tenacious efforts finally succeeded."],
  ["steadfast", "adjective", "Resolutely firm and unwavering", "He remained steadfast in his beliefs.", "Steadfast loyalty defined their friendship."],
  ["resolute", "adjective", "Admirably purposeful and determined", "She was resolute in her decision.", "Resolute action was needed."],
  ["unwavering", "adjective", "Steady and constant", "His unwavering support meant everything.", "Unwavering focus led to success."],
  ["indomitable", "adjective", "Impossible to subdue or defeat", "Her indomitable spirit inspired many.", "The team showed indomitable will."],
  ["invincible", "adjective", "Too powerful to be defeated", "They felt invincible that day.", "No one is truly invincible."],
  ["intrepid", "adjective", "Fearless and adventurous", "Intrepid explorers braved the unknown.", "Her intrepid nature took her far."],
  ["dauntless", "adjective", "Showing fearlessness", "The dauntless knight rode into battle.", "Dauntless courage defined her."],
  ["valiant", "adjective", "Possessing courage and determination", "Valiant soldiers defended the city.", "A valiant effort fell just short."],
  ["gallant", "adjective", "Brave and noble; courteous to women", "The gallant knight saved the day.", "His gallant behavior charmed everyone."],
  ["chivalrous", "adjective", "Courteous and gallant, especially to women", "His chivalrous manner impressed her.", "Chivalrous deeds were expected of knights."],
  ["noble", "adjective", "Having high moral qualities", "A noble gesture touched their hearts.", "Noble intentions guided his actions."],
  ["virtuous", "adjective", "Having high moral standards", "She led a virtuous life.", "Virtuous behavior is its own reward."],
  ["righteous", "adjective", "Morally right or justifiable", "Righteous anger fueled the protest.", "He felt righteous in his cause."],
  ["upright", "adjective", "Strictly honest and respectable", "An upright citizen, she was trusted.", "Upright conduct earned respect."],
  ["principled", "adjective", "Acting according to moral principles", "A principled stand cost him the job.", "Principled leaders are rare."],
  ["scrupulous", "adjective", "Diligent and thorough; ethical", "Scrupulous attention to detail showed.", "She was scrupulous in her dealings."],
  ["meticulous", "adjective", "Very careful and precise", "Meticulous planning ensured success.", "Her meticulous nature was an asset."],
  ["fastidious", "adjective", "Very attentive to detail", "Fastidious about cleanliness, she scrubbed daily.", "His fastidious taste was legendary."],
  ["punctilious", "adjective", "Showing great attention to detail", "Punctilious about etiquette, he never erred.", "Punctilious record-keeping saved them."],
  ["assiduous", "adjective", "Showing great care and perseverance", "Assiduous efforts led to discovery.", "Her assiduous research was thorough."],
  ["diligent", "adjective", "Having careful and persistent work", "Diligent students excel.", "Diligent practice makes perfect."],
  ["industrious", "adjective", "Hard-working and busy", "Industrious workers built the city.", "The industrious bee inspired them."],
  ["sedulous", "adjective", "Showing dedication and diligence", "Sedulous attention to duty impressed all.", "Her sedulous nature ensured quality."],
  ["zealous", "adjective", "Having great energy for a cause", "Zealous supporters rallied.", "His zealous advocacy made a difference."],
  ["fervent", "adjective", "Having intense feeling", "Fervent prayers filled the church.", "Her fervent hope never dimmed."],
  ["ardent", "adjective", "Enthusiastic or passionate", "An ardent supporter of the arts.", "Ardent love letters arrived daily."],
  ["passionate", "adjective", "Showing strong feelings", "Passionate debate ensued.", "She was passionate about justice."],
  ["vehement", "adjective", "Showing strong feeling", "Vehement protests erupted.", "His vehement denial convinced no one."],
  ["fervor", "noun", "Intense and passionate feeling", "Religious fervor swept the land.", "Revolutionary fervor was rising."],
  ["zeal", "noun", "Great energy in pursuit of a cause", "Missionary zeal drove them forward.", "His zeal was sometimes excessive."],
  ["ardor", "noun", "Enthusiasm or passion", "Youthful ardor knew no bounds.", "The ardor of first love faded."],
  ["verve", "noun", "Vigor and spirit in expression", "She performed with verve.", "His writing had real verve."],
  ["panache", "noun", "Flamboyant confidence of style", "He dressed with panache.", "Her panache on stage was legendary."],
  ["élan", "noun", "Energy and enthusiasm", "The team played with élan.", "Her élan was infectious."],
  ["gusto", "noun", "Enjoyment and enthusiasm", "He ate with gusto.", "They tackled the project with gusto."],
  ["relish", "noun", "Great enjoyment", "She relished the challenge.", "He told the story with relish."],
  ["zest", "noun", "Great enthusiasm and energy", "Her zest for life was inspiring.", "Add some zest to your routine."],
  ["vigor", "noun", "Physical strength and energy", "Despite his age, he had vigor.", "Renewed vigor marked her return."],
  ["vitality", "noun", "The state of being full of life", "The city has great vitality.", "Her vitality was remarkable."],
  ["dynamism", "noun", "The quality of being energetic", "The team's dynamism was impressive.", "Her dynamism transformed the company."],
  ["vivacity", "noun", "Attractively lively quality", "Her vivacity charmed everyone.", "The party had great vivacity."],
  ["sprightliness", "noun", "Liveliness and high spirits", "Age hadn't diminished her sprightliness.", "The sprightliness of the dance delighted."],
  ["buoyancy", "noun", "Cheerful and optimistic attitude", "His buoyancy lifted everyone.", "Market buoyancy continued."],
  ["jauntiness", "noun", "A lively and cheerful manner", "There was a jauntiness in his step.", "Her jauntiness was appealing."],
  ["breeziness", "noun", "A casual and cheerful manner", "His breeziness put people at ease.", "The breeziness of the writing engaged readers."],
  ["lightness", "noun", "The quality of being not heavy; cheerfulness", "A lightness entered her heart.", "The lightness of the fabric was perfect."],
  ["airiness", "noun", "The quality of being spacious and well-ventilated", "The airiness of the room was refreshing.", "An airiness in her manner charmed all."],
  ["brightness", "noun", "The quality of giving out light", "The brightness of the sun warmed them.", "Her brightness lifted everyone's mood."],
  ["radiance", "noun", "Light or heat emanating from something", "The radiance of the fire was welcoming.", "Her radiance outshone the stars."],
  ["glow", "noun", "A steady radiance of light or heat", "The glow of candles softened the room.", "A glow of satisfaction filled her."],
  ["warmth", "noun", "The quality of having moderate heat", "The warmth of the sun felt good.", "Her warmth made everyone feel welcome."],
  ["coziness", "noun", "The quality of being warm and comfortable", "The coziness of the cabin was inviting.", "They enjoyed the coziness of home."],
  ["snugness", "noun", "The quality of being comfortable and warm", "The snugness of the blanket helped her sleep.", "Snugness characterized the small space."],
  ["comfort", "noun", "A state of physical ease", "The chair provided great comfort.", "They found comfort in each other."],
  ["solace", "noun", "Comfort in sorrow or misfortune", "Music provided solace.", "She found solace in nature."],
  ["consolation", "noun", "Comfort received after a loss", "Her words were a consolation.", "Small consolations helped them cope."],
  ["succor", "noun", "Assistance and support in distress", "They provided succor to refugees.", "Succor arrived in time."],
  ["respite", "noun", "A short rest from difficulty", "The weekend offered respite.", "A brief respite refreshed them."],
  ["repose", "noun", "A state of rest or tranquility", "She found repose in the garden.", "His face showed peaceful repose."],
  ["quietude", "noun", "A state of stillness and calm", "The quietude of dawn soothed her.", "Quietude descended on the house."],
  ["stillness", "noun", "The absence of movement or sound", "The stillness of the forest was eerie.", "In the stillness, she could think."],
  ["hush", "noun", "A silence or stillness", "A hush fell over the crowd.", "The hush before dawn was peaceful."],
  ["silence", "noun", "Complete absence of sound", "Silence filled the room.", "In silence, they contemplated."],
  ["taciturnity", "noun", "Reserved or uncommunicative manner", "His taciturnity puzzled newcomers.", "Her taciturnity was often misunderstood."],
  ["reticence", "noun", "The quality of being reserved", "His reticence about his past was notable.", "She broke her usual reticence."],
  ["discretion", "noun", "The quality of being discreet", "Discretion is valued in this role.", "Use discretion when sharing."],
  ["prudence", "noun", "The quality of being prudent", "Prudence guided her choices.", "Financial prudence paid off."],
  ["circumspection", "noun", "The quality of being cautious", "Circumspection prevented mistakes.", "His circumspection served him well."],
  ["wariness", "noun", "Caution about possible dangers", "Wariness colored his approach.", "Her wariness was understandable."],
  ["vigilance", "noun", "The action of keeping watch", "Vigilance prevented accidents.", "Eternal vigilance is required."],
  ["alertness", "noun", "The quality of being quick to notice", "Her alertness saved them.", "Mental alertness declined late at night."],
  ["acuity", "noun", "Sharpness of thought or vision", "Visual acuity decreased with age.", "Her mental acuity impressed everyone."],
  ["keenness", "noun", "The quality of being eager", "His keenness to learn was evident.", "Keenness of hearing helped hunters."],
  ["sharpness", "noun", "The quality of being able to cut", "The knife's sharpness was tested.", "Sharpness of wit defined her humor."],
  ["acerbity", "noun", "Sharpness of speech or manner", "Her acerbity surprised newcomers.", "The acerbity of the review stung."],
  ["asperity", "noun", "Harshness of tone or manner", "He spoke with unexpected asperity.", "The asperity of winter was brutal."],
  ["tartness", "noun", "Sharpness of taste or manner", "The apple's tartness was refreshing.", "Her tartness concealed affection."],
  ["piquancy", "noun", "A pleasantly sharp quality", "The sauce had nice piquancy.", "Piquancy characterized her wit."],
  ["pungency", "noun", "Having a sharply strong taste or smell", "The pungency of garlic filled the kitchen.", "Pungency marked his commentary."],
  ["sapidity", "noun", "The quality of having flavor", "The sapidity of the dish impressed critics.", "Good cooking emphasizes sapidity."],
  ["savory", "adjective", "Having an appetizing taste or smell", "Savory aromas filled the kitchen.", "The savory pie was delicious."],
  ["toothsome", "adjective", "Temptingly tasty", "The toothsome dessert disappeared quickly.", "A toothsome meal awaited them."],
  ["delectable", "adjective", "Delicious and delightful", "Delectable treats lined the table.", "The view was equally delectable."],
  ["scrumptious", "adjective", "Extremely appetizing", "The scrumptious cake was gone in minutes.", "What a scrumptious meal!"],
  ["sumptuous", "adjective", "Splendid and expensive-looking", "A sumptuous feast was prepared.", "The sumptuous decor impressed guests."],
  ["opulent", "adjective", "Ostentatiously rich and luxurious", "The opulent palace dazzled visitors.", "Opulent fabrics adorned the room."],
  ["lavish", "adjective", "Sumptuously rich or elaborate", "A lavish wedding was planned.", "Lavish praise embarrassed her."],
  ["luxuriant", "adjective", "Rich and profuse in growth", "Luxuriant vegetation covered the hillside.", "Her luxuriant hair cascaded down."],
  ["lush", "adjective", "Growing luxuriantly", "Lush gardens surrounded the estate.", "The lush green valley invited exploration."],
  ["verdure", "noun", "The lush greenness of flourishing vegetation", "Spring brought verdure to the hills.", "The verdure was a feast for the eyes."],
  ["foliage", "noun", "Plant leaves collectively", "Autumn foliage attracted tourists.", "Dense foliage blocked the view."],
  ["canopy", "noun", "An ornamental covering; treetop layer", "The forest canopy filtered sunlight.", "A canopy of stars appeared."]
];

// Combine all words
let allWords = [
  ...words,
  ...moreWords,
  ...additionalWords.map(w => ({ word: w[0], pos: w[1], definition: w[2], examples: [w[3], w[4]] })),
  ...moreWords2.map(w => ({ word: w[0], pos: w[1], definition: w[2], examples: [w[3], w[4]] })),
  ...moreWords3.map(w => ({ word: w[0], pos: w[1], definition: w[2], examples: [w[3], w[4]] }))
];

// More words to fill remaining slots
const fillWords = [
  ["cynosure", "noun", "A center of attention or attraction", "She was the cynosure of all eyes.", "The fountain was the garden's cynosure."],
  ["quiddity", "noun", "The inherent nature of something", "He captured the quiddity of the moment.", "The quiddity of love remains elusive."],
  ["anodyne", "adjective", "Not likely to cause offense; bland", "His anodyne remarks bored the crowd.", "The speech was pleasant but anodyne."],
  ["dulcify", "verb", "To make sweet or soothe", "Honey dulcifies bitter medicine.", "Her words dulcified his anger."],
  ["susurrate", "verb", "To make a whispering or rustling sound", "Leaves susurrated in the breeze.", "The stream susurrated over stones."],
  ["coruscant", "adjective", "Sparkling or gleaming", "Coruscant light danced on the waves.", "Her coruscant jewelry caught attention."],
  ["refulgent", "adjective", "Shining very brightly", "The refulgent sun rose majestically.", "Her refulgent beauty stunned him."],
  ["lambency", "noun", "A soft radiance", "The lambency of firelight was soothing.", "Lambency emanated from her smile."],
  ["felicitous", "adjective", "Well-suited for the occasion", "A felicitous phrase captured the mood.", "The timing was felicitous."],
  ["propitious", "adjective", "Giving a good chance of success", "Conditions were propitious for growth.", "The propitious moment arrived."],
  ["auspicious", "adjective", "Conducive to success; favorable", "An auspicious beginning cheered them.", "The signs were auspicious."],
  ["fortuitous", "adjective", "Happening by lucky chance", "Their meeting was fortuitous.", "A fortuitous discovery changed everything."],
  ["serendipitous", "adjective", "Occurring by happy chance", "A serendipitous encounter changed her life.", "The discovery was serendipitous."],
  ["providential", "adjective", "Occurring at a favorable time", "His arrival was providential.", "Providential intervention saved the day."],
  ["opportune", "adjective", "Occurring at a good time", "An opportune moment presented itself.", "The timing was opportune."],
  ["timely", "adjective", "Done or occurring at a good time", "Timely advice prevented disaster.", "Her arrival was timely."],
  ["apposite", "adjective", "Apt in the circumstances", "An apposite quotation enriched the speech.", "Her remarks were apposite."],
  ["apropos", "adjective", "Very appropriate to a situation", "His comment was apropos.", "Apropos of nothing, she laughed."],
  ["germane", "adjective", "Relevant to a subject", "Only germane facts were included.", "Is this germane to the discussion?"],
  ["pertinent", "adjective", "Relevant or applicable", "Pertinent questions were asked.", "The information was pertinent."],
  ["salient", "adjective", "Most noticeable or important", "The salient points were summarized.", "Salient features were highlighted."],
  ["cogent", "adjective", "Clear, logical, and convincing", "A cogent argument won the day.", "Her reasoning was cogent."],
  ["compelling", "adjective", "Evoking interest and attention", "A compelling narrative emerged.", "The evidence was compelling."],
  ["persuasive", "adjective", "Good at inducing belief", "Her persuasive tone convinced them.", "A persuasive case was made."],
  ["eloquence", "noun", "Fluent or persuasive speaking", "His eloquence moved the audience.", "Eloquence is a valuable skill."],
  ["oratory", "noun", "The art of public speaking", "His oratory inspired millions.", "Oratory was prized in ancient times."],
  ["rhetoric", "noun", "The art of effective speaking", "The rhetoric was powerful but empty.", "Ancient rhetoric still influences us."],
  ["articulate", "adjective", "Having the ability to speak fluently", "She was articulate and convincing.", "An articulate speaker always impresses."],
  ["voluble", "adjective", "Speaking fluently and at length", "The voluble host entertained everyone.", "His voluble nature sometimes annoyed."],
  ["loquacious", "adjective", "Tending to talk a great deal", "The loquacious guide shared many stories.", "She became more loquacious with wine."],
  ["garrulous", "adjective", "Excessively talkative", "The garrulous neighbor knew all gossip.", "His garrulous tendencies tired listeners."],
  ["verbose", "adjective", "Using more words than needed", "The verbose report tested patience.", "His verbose style obscured his point."],
  ["prolix", "adjective", "Using too many words; tediously long", "The prolix speaker lost the audience.", "Prolix descriptions slowed the novel."],
  ["terse", "adjective", "Sparing in the use of words", "Her terse reply ended the discussion.", "Terse instructions were appreciated."],
  ["laconic", "adjective", "Using very few words", "His laconic style was effective.", "A laconic response was all he gave."],
  ["succinct", "adjective", "Briefly and clearly expressed", "A succinct summary was provided.", "Her succinct explanation helped."],
  ["pithy", "adjective", "Concise and forcefully expressive", "Pithy aphorisms filled the book.", "Her pithy remarks were memorable."],
  ["trenchant", "adjective", "Vigorous and incisive", "Trenchant criticism stung the author.", "His trenchant analysis cut through confusion."],
  ["incisive", "adjective", "Showing clear thought and understanding", "Incisive questions revealed the truth.", "Her incisive mind impressed everyone."],
  ["astute", "adjective", "Having sharp judgment", "An astute observer noticed the clue.", "His astute analysis proved correct."],
  ["shrewd", "adjective", "Having sharp powers of judgment", "A shrewd businesswoman, she prospered.", "Shrewd investments built her fortune."],
  ["canny", "adjective", "Having good judgment", "The canny investor avoided the crash.", "Her canny sense guided decisions."],
  ["sagacious", "adjective", "Having acute mental discernment", "The sagacious elder advised wisely.", "Sagacious leaders anticipate problems."],
  ["sapient", "adjective", "Wise or attempting to appear wise", "Sapient beings seek understanding.", "His sapient advice was valued."],
  ["erudite", "adjective", "Having great knowledge from studying", "The erudite professor lectured brilliantly.", "Her erudite commentary enriched the discussion."],
  ["scholarly", "adjective", "Involving serious academic study", "Scholarly analysis revealed new insights.", "His scholarly work was widely cited."],
  ["learned", "adjective", "Having acquired much knowledge", "The learned doctor wrote extensively.", "Learned discussion followed the lecture."],
  ["cultivated", "adjective", "Refined and well-educated", "Her cultivated taste was evident.", "Cultivated manners impressed everyone."],
  ["refined", "adjective", "Elegant and cultured", "Refined tastes guided her choices.", "His refined manner charmed guests."],
  ["sophisticated", "adjective", "Having worldly knowledge", "A sophisticated palate appreciated subtlety.", "Sophisticated analysis was required."],
  ["urbane", "adjective", "Courteous and refined", "His urbane wit entertained the guests.", "Urbane sophistication marked his style."],
  ["suave", "adjective", "Charming and sophisticated", "The suave gentleman impressed everyone.", "His suave manner won them over."],
  ["debonair", "adjective", "Confident and stylish", "The debonair actor charmed audiences.", "His debonair appearance attracted attention."],
  ["dapper", "adjective", "Neat and trim in dress", "The dapper gentleman turned heads.", "Always dapper, he took pride in appearance."],
  ["natty", "adjective", "Smart and fashionable", "His natty suit impressed the interviewer.", "She looked natty in her new outfit."],
  ["spruce", "adjective", "Neat in dress and appearance", "He looked spruce for the interview.", "The spruce garden showed care."],
  ["immaculate", "adjective", "Perfectly clean or tidy", "The immaculate house impressed visitors.", "Her immaculate record stood out."],
  ["pristine", "adjective", "In its original condition", "Pristine wilderness awaited explorers.", "The car was in pristine condition."],
  ["spotless", "adjective", "Absolutely clean or pure", "The spotless kitchen gleamed.", "Her spotless reputation was deserved."],
  ["unsullied", "adjective", "Not spoiled or made impure", "His unsullied reputation preceded him.", "The unsullied snow sparkled."],
  ["unblemished", "adjective", "Not damaged or marked", "An unblemished record impressed employers.", "Her unblemished skin glowed."],
  ["flawless", "adjective", "Without any blemishes or imperfections", "A flawless performance earned standing ovation.", "The diamond was flawless."],
  ["impeccable", "adjective", "Without faults or errors", "Her impeccable taste was renowned.", "Impeccable timing made the joke land."],
  ["consummate", "adjective", "Showing great skill and flair", "A consummate professional in every way.", "His consummate artistry moved audiences."],
  ["peerless", "adjective", "Unequaled or unrivaled", "Her peerless beauty inspired poets.", "His peerless skill won championships."],
  ["matchless", "adjective", "Incomparable or unequaled", "Matchless craftsmanship defined the piece.", "Her matchless grace enchanted everyone."],
  ["unparalleled", "adjective", "Having no parallel or equal", "Unparalleled success followed.", "Her achievements were unparalleled."],
  ["incomparable", "adjective", "Beyond comparison", "Incomparable beauty characterized the view.", "His talent was incomparable."],
  ["transcendent", "adjective", "Beyond ordinary limits", "A transcendent experience changed her.", "His transcendent genius was recognized."],
  ["superlative", "adjective", "Of the highest quality", "Superlative work earned recognition.", "The view was superlative."],
  ["supreme", "adjective", "Highest in rank or authority", "Supreme confidence marked his approach.", "The supreme court ruled."],
  ["paramount", "adjective", "More important than anything else", "Safety is paramount.", "Paramount concerns were addressed."],
  ["preeminent", "adjective", "Surpassing all others", "The preeminent scholar in her field.", "His preeminent status was undisputed."],
  ["foremost", "adjective", "Most prominent in rank or importance", "The foremost expert was consulted.", "He was foremost among equals."],
  ["quintessential", "adjective", "Representing the perfect example", "The quintessential English gentleman.", "It was the quintessential summer day."],
  ["archetypal", "adjective", "Very typical of a certain kind", "An archetypal hero's journey unfolded.", "The archetypal villain appeared."],
  ["paradigmatic", "adjective", "Serving as a typical example", "A paradigmatic case was studied.", "Her career was paradigmatic of success."],
  ["exemplary", "adjective", "Serving as a desirable model", "Exemplary behavior earned praise.", "His exemplary service was recognized."],
  ["laudable", "adjective", "Deserving praise and commendation", "A laudable effort was made.", "Her laudable goals inspired others."],
  ["commendable", "adjective", "Deserving praise", "Commendable work earned recognition.", "His commendable patience impressed all."],
  ["admirable", "adjective", "Arousing respect and approval", "Admirable qualities defined her.", "His admirable courage was noted."],
  ["estimable", "adjective", "Worthy of great respect", "An estimable colleague was lost.", "Her estimable contributions were celebrated."],
  ["venerable", "adjective", "Accorded great respect due to age or wisdom", "The venerable institution celebrated its centenary.", "Venerable traditions were maintained."],
  ["august", "adjective", "Respected and impressive", "The august assembly convened.", "His august presence commanded attention."],
  ["distinguished", "adjective", "Successful and respected", "A distinguished career came to close.", "The distinguished professor lectured."],
  ["eminent", "adjective", "Famous and respected", "Eminent scholars gathered.", "Her eminence in the field was recognized."],
  ["illustrious", "adjective", "Well-known and admired", "An illustrious history preceded them.", "Illustrious guests attended."],
  ["renowned", "adjective", "Known and admired by many", "The renowned artist exhibited.", "Her renowned expertise was sought."],
  ["celebrated", "adjective", "Greatly admired and acclaimed", "The celebrated author spoke.", "A celebrated victory followed."],
  ["acclaimed", "adjective", "Publicly praised and celebrated", "The acclaimed film won awards.", "Her acclaimed novel sold millions."],
  ["esteemed", "adjective", "Respected and admired", "The esteemed colleague was honored.", "Esteemed guests were welcomed."],
  ["revered", "adjective", "Deeply respected and admired", "The revered leader passed away.", "Revered traditions continued."],
  ["exalted", "adjective", "Of high rank or status", "Exalted expectations were set.", "His exalted position brought responsibility."],
  ["sublime", "adjective", "Of outstanding spiritual or artistic worth", "Sublime beauty surrounded them.", "A sublime performance moved all."],
  ["majestic", "adjective", "Having impressive beauty or dignity", "Majestic mountains rose in the distance.", "The majestic eagle soared."],
  ["stately", "adjective", "Having dignity and grandeur", "Stately homes lined the avenue.", "Her stately presence impressed."],
  ["grandiose", "adjective", "Impressive but exaggerated", "Grandiose plans were proposed.", "The grandiose building dominated."],
  ["magnificent", "adjective", "Extremely beautiful and impressive", "Magnificent views rewarded climbers.", "A magnificent performance closed the show."],
  ["splendid", "adjective", "Magnificent and impressive", "Splendid architecture characterized the city.", "A splendid time was had."],
  ["glorious", "adjective", "Having great beauty and splendor", "A glorious sunset painted the sky.", "Glorious victory was celebrated."],
  ["resplendent", "adjective", "Impressive through rich colors", "Resplendent in gold, she entered.", "The resplendent palace amazed visitors."],
  ["dazzling", "adjective", "Extremely bright or impressive", "Dazzling lights illuminated the stage.", "Her dazzling smile won hearts."],
  ["breathtaking", "adjective", "Astonishing or awe-inspiring", "Breathtaking scenery surrounded them.", "A breathtaking performance followed."],
  ["awe-inspiring", "adjective", "Causing feelings of respect and wonder", "The awe-inspiring cathedral towered above.", "His awe-inspiring courage was legendary."],
  ["wondrous", "adjective", "Inspiring a feeling of wonder", "Wondrous sights awaited travelers.", "The wondrous display amazed children."],
  ["marvelous", "adjective", "Causing great wonder", "A marvelous achievement was celebrated.", "Marvelous news arrived."],
  ["miraculous", "adjective", "Like a miracle; remarkable", "A miraculous recovery followed.", "Her miraculous escape made headlines."],
  ["extraordinary", "adjective", "Very unusual or remarkable", "Extraordinary circumstances warranted action.", "His extraordinary talent was evident."],
  ["phenomenal", "adjective", "Remarkable or exceptional", "Phenomenal success followed.", "Her phenomenal rise surprised everyone."],
  ["prodigious", "adjective", "Remarkably great in extent", "Prodigious talent was displayed.", "His prodigious memory amazed scholars."],
  ["stupendous", "adjective", "Extremely impressive", "Stupendous views greeted them.", "A stupendous effort was made."],
  ["tremendous", "adjective", "Very great in amount or level", "Tremendous progress was achieved.", "Tremendous applause followed."],
  ["immense", "adjective", "Extremely large or great", "Immense challenges lay ahead.", "Immense gratitude was expressed."],
  ["colossal", "adjective", "Extremely large", "Colossal statues lined the avenue.", "A colossal mistake was made."],
  ["monumental", "adjective", "Great in importance or size", "Monumental achievements were recognized.", "A monumental task awaited them."],
  ["gargantuan", "adjective", "Enormous in size", "Gargantuan appetites were satisfied.", "The gargantuan project was completed."],
  ["titanic", "adjective", "Of exceptional strength or size", "Titanic efforts were required.", "A titanic struggle ensued."],
  ["herculean", "adjective", "Requiring great strength or effort", "A Herculean task faced them.", "Herculean labor built the dam."],
  ["formidable", "adjective", "Inspiring fear or respect", "A formidable opponent waited.", "Formidable challenges were overcome."],
  ["redoubtable", "adjective", "Formidable, especially as an opponent", "The redoubtable champion defended her title.", "His redoubtable reputation preceded him."],
  ["indefatigable", "adjective", "Persisting tirelessly", "Her indefatigable spirit inspired others.", "Indefatigable efforts led to success."],
  ["inexhaustible", "adjective", "Incapable of being used up", "Her inexhaustible energy amazed everyone.", "An inexhaustible supply was found."],
  ["unremitting", "adjective", "Never relaxing or slackening", "Unremitting effort finally paid off.", "Unremitting rain flooded the streets."],
  ["relentless", "adjective", "Oppressively constant", "Relentless pursuit of excellence defined her.", "The relentless heat exhausted them."],
  ["persistent", "adjective", "Continuing firmly despite difficulty", "Persistent effort achieved results.", "Her persistent questioning revealed truth."],
  ["dogged", "adjective", "Having determination", "Dogged determination saw her through.", "His dogged pursuit finally succeeded."],
  ["unflagging", "adjective", "Tireless and persistent", "Unflagging enthusiasm inspired the team.", "Her unflagging support was invaluable."],
  ["untiring", "adjective", "Continuing at the same level of effort", "Untiring efforts finally bore fruit.", "His untiring dedication was admired."],
  ["tireless", "adjective", "Having great energy and determination", "Tireless work achieved the goal.", "Her tireless advocacy made a difference."],
  ["energetic", "adjective", "Showing great activity or vitality", "Energetic performances delighted audiences.", "The energetic child exhausted babysitters."],
  ["spirited", "adjective", "Full of energy and determination", "Spirited debate enlivened the meeting.", "Her spirited defense impressed the jury."],
  ["animated", "adjective", "Full of life or excitement", "Animated discussion followed the lecture.", "Her animated storytelling captivated."],
  ["ebullient", "adjective", "Cheerful and full of energy", "His ebullient personality lit up rooms.", "Ebullient crowds celebrated."],
  ["exuberant", "adjective", "Filled with lively energy", "Exuberant fans cheered wildly.", "Her exuberant laughter was infectious."],
  ["vibrant", "adjective", "Full of energy and life", "A vibrant community thrived there.", "Vibrant colors filled the market."],
  ["vivid", "adjective", "Producing powerful images in the mind", "Vivid memories remained.", "Her vivid imagination created worlds."],
  ["striking", "adjective", "Attracting attention by being unusual", "A striking resemblance was noted.", "Her striking beauty turned heads."],
  ["arresting", "adjective", "Striking and attracting attention", "An arresting image dominated the page.", "Her arresting gaze held him."],
  ["captivating", "adjective", "Capable of attracting and holding attention", "A captivating story unfolded.", "Her captivating smile enchanted everyone."],
  ["enthralling", "adjective", "Capturing attention completely", "An enthralling performance followed.", "The enthralling novel kept readers up."],
  ["spellbinding", "adjective", "Holding attention as if by a spell", "Spellbinding oratory moved the crowd.", "The spellbinding view held them."],
  ["mesmerizing", "adjective", "Capturing attention completely", "Mesmerizing beauty surrounded them.", "His mesmerizing performance won acclaim."],
  ["hypnotic", "adjective", "Exerting a compelling quality", "The hypnotic rhythm lulled them.", "Her hypnotic voice entranced listeners."],
  ["entrancing", "adjective", "Filling with wonder and delight", "Entrancing music filled the hall.", "The entrancing beauty of nature inspired."],
  ["enchanting", "adjective", "Delightfully charming", "An enchanting melody played.", "The enchanting village welcomed visitors."],
  ["bewitching", "adjective", "Enchanting and delightful", "Her bewitching smile captivated all.", "The bewitching landscape inspired artists."],
  ["alluring", "adjective", "Powerfully attractive", "An alluring fragrance drew them closer.", "Her alluring charm was irresistible."],
  ["beguiling", "adjective", "Charming in a deceptive way", "His beguiling manner hid his intentions.", "A beguiling smile disarmed critics."],
  ["engaging", "adjective", "Charming and attractive", "Her engaging personality won friends.", "An engaging speaker held attention."],
  ["winning", "adjective", "Attractive and appealing", "His winning smile charmed everyone.", "A winning combination emerged."],
  ["prepossessing", "adjective", "Attractive or appealing", "His prepossessing manner impressed.", "A prepossessing appearance helped."],
  ["personable", "adjective", "Having a pleasant appearance and manner", "The personable host made guests comfortable.", "Her personable nature won many friends."],
  ["affable", "adjective", "Friendly and easy to talk to", "The affable manager was well-liked.", "His affable manner put people at ease."],
  ["amiable", "adjective", "Having a friendly disposition", "The amiable host welcomed everyone.", "Her amiable nature made her popular."],
  ["congenial", "adjective", "Pleasant and agreeable", "A congenial atmosphere prevailed.", "Congenial colleagues made work enjoyable."],
  ["genial", "adjective", "Friendly and cheerful", "His genial manner was welcoming.", "A genial smile greeted visitors."],
  ["jovial", "adjective", "Cheerful and friendly", "The jovial host kept spirits high.", "His jovial nature was infectious."],
  ["convivial", "adjective", "Friendly and enjoyable", "Convivial gatherings were frequent.", "The convivial atmosphere encouraged conversation."],
  ["gregarious", "adjective", "Fond of company", "Her gregarious nature drew many friends.", "Gregarious by nature, he enjoyed parties."],
  ["sociable", "adjective", "Willing to talk and engage with others", "The sociable host mingled with guests.", "A sociable gathering ensued."],
  ["outgoing", "adjective", "Friendly and sociable", "Her outgoing personality made friends easily.", "The outgoing child charmed everyone."],
  ["extroverted", "adjective", "Outgoing and socially confident", "His extroverted nature suited sales.", "Extroverted leaders often emerge naturally."],
  ["effusive", "adjective", "Expressing feelings freely", "Effusive praise followed the performance.", "Her effusive welcome embarrassed him."],
  ["gushing", "adjective", "Expressing admiration excessively", "Gushing reviews greeted the film.", "Her gushing enthusiasm was genuine."],
  ["effervescent", "adjective", "Vivacious and enthusiastic", "Her effervescent personality lit up rooms.", "Effervescent wit enlivened the party."]
];

// Add remaining words
allWords = allWords.concat(fillWords.map(w => ({ word: w[0], pos: w[1], definition: w[2], examples: [w[3], w[4]] })));

// Ensure we have exactly 1000 words, remove duplicates
const seen = new Set();
const uniqueWords = [];
for (const w of allWords) {
  if (!seen.has(w.word.toLowerCase())) {
    seen.add(w.word.toLowerCase());
    uniqueWords.push(w);
  }
}

console.log(`Generated ${uniqueWords.length} unique words`);

// Write to file
const outputPath = resolve(dataDir, 'words.json');
writeFileSync(outputPath, JSON.stringify(uniqueWords, null, 2));
console.log(`Words saved to ${outputPath}`);

