import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = resolve(__dirname, '../src/data/words.json');

// Read existing words
const existingWords = JSON.parse(readFileSync(dataPath, 'utf-8'));
const existingSet = new Set(existingWords.map(w => w.word.toLowerCase()));

// Additional words to reach 1000
const additionalWords = [
  ["luminous", "adjective", "Full of or shedding light", "The luminous moon lit the path.", "Her luminous eyes sparkled."],
  ["lustrous", "adjective", "Having luster; shining", "Lustrous silk draped the table.", "Her lustrous hair gleamed."],
  ["pellucid", "adjective", "Translucently clear", "Pellucid waters revealed the bottom.", "His pellucid prose was praised."],
  ["crystalline", "adjective", "Having the structure of a crystal", "Crystalline formations dazzled visitors.", "Her crystalline voice rang out."],
  ["prismatic", "adjective", "Of or like a prism", "Prismatic light scattered rainbows.", "Her prismatic imagination created wonders."],
  ["kaleidoscopic", "adjective", "Having complex patterns of colors", "Kaleidoscopic visions filled her dreams.", "The kaleidoscopic display amazed all."],
  ["chromatic", "adjective", "Relating to colors", "Chromatic scales challenged the pianist.", "The chromatic beauty stunned viewers."],
  ["polychromatic", "adjective", "Having several colors", "Polychromatic fabrics brightened the room.", "The polychromatic sunset amazed tourists."],
  ["variegated", "adjective", "Exhibiting different colors", "Variegated leaves decorated the garden.", "Her variegated interests were impressive."],
  ["mottled", "adjective", "Marked with spots of color", "Mottled sunlight filtered through leaves.", "The mottled stone was unique."],
  ["dappled", "adjective", "Marked with spots or patches", "Dappled shadows played on the grass.", "The dappled fawn hid in the forest."],
  ["speckled", "adjective", "Covered with small spots", "Speckled eggs filled the nest.", "Her speckled complexion was charming."],
  ["flecked", "adjective", "Marked with small patches of color", "Flecked marble adorned the hall.", "His eyes were flecked with gold."],
  ["stippled", "adjective", "Marked with dots or small spots", "The stippled effect created texture.", "Stippled light illuminated the scene."],
  ["tessellated", "adjective", "Decorated with mosaic patterns", "Tessellated floors graced the palace.", "The tessellated design was intricate."],
  ["baroque", "adjective", "Highly ornate and extravagant", "Baroque architecture dominated the city.", "His baroque prose was exhausting."],
  ["rococo", "adjective", "Ornately decorated", "Rococo furnishings filled the salon.", "The rococo style seemed excessive."],
  ["ornate", "adjective", "Elaborately decorated", "Ornate carvings adorned the temple.", "Her ornate handwriting was beautiful."],
  ["florid", "adjective", "Elaborately intricate", "His florid prose tired readers.", "Florid decorations overwhelmed the space."],
  ["embellished", "adjective", "Made more attractive by additions", "The embellished manuscript was priceless.", "Her embellished story entertained all."],
  ["adorned", "adjective", "Made more beautiful with decorations", "The adorned hall welcomed guests.", "She was adorned with jewels."],
  ["festooned", "adjective", "Decorated with garlands", "The room was festooned with flowers.", "Festooned balconies lined the street."],
  ["bedecked", "adjective", "Decorated or adorned", "The hall was bedecked with lights.", "She was bedecked in her finest."],
  ["garlanded", "adjective", "Crowned with a garland", "The winner was garlanded with flowers.", "Garlanded statues filled the temple."],
  ["wreathed", "adjective", "Encircled or adorned", "The door was wreathed in holly.", "Her face was wreathed in smiles."],
  ["entwined", "adjective", "Twisted together", "Their fates were entwined forever.", "Entwined vines covered the wall."],
  ["intertwined", "adjective", "Twisted or linked together", "Their stories were intertwined.", "Intertwined roots bound the trees."],
  ["interwoven", "adjective", "Blended or mixed together", "Interwoven threads created the pattern.", "Their lives were interwoven."],
  ["interlaced", "adjective", "Crossed intricately together", "Interlaced patterns decorated the border.", "The interlaced branches formed a canopy."],
  ["filigree", "noun", "Ornamental work of fine wire", "Silver filigree adorned the box.", "The filigree work was exquisite."],
  ["tracery", "noun", "Ornamental stonework patterns", "Gothic tracery filled the window.", "Delicate tracery decorated the ceiling."],
  ["lacework", "noun", "Delicate ornamental fabric", "Fine lacework bordered the cloth.", "Her fingers created beautiful lacework."],
  ["brocade", "noun", "Rich fabric with raised patterns", "Silk brocade covered the chairs.", "The brocade curtains were magnificent."],
  ["damask", "noun", "Fabric with woven patterns", "Damask tablecloths graced the dinner.", "Fine damask adorned the walls."],
  ["tapestry", "noun", "A piece of thick textile art", "Medieval tapestries warmed the castle.", "Life is a rich tapestry."],
  ["mosaic", "noun", "A picture made of small pieces", "Roman mosaics decorated the floor.", "The mosaic revealed an ancient story."],
  ["fresco", "noun", "A mural painted on plaster", "The fresco depicted heavenly scenes.", "Renaissance frescoes adorned the chapel."],
  ["patina", "noun", "A sheen from age or use", "Bronze develops a green patina.", "The antique had a lovely patina."],
  ["verdigris", "noun", "Greenish coating on copper", "Verdigris covered the old statue.", "The verdigris showed its age."],
  ["vintage", "adjective", "Of high quality from the past", "Vintage wines aged in the cellar.", "Her vintage style was distinctive."],
  ["antique", "adjective", "Valuable because of its age", "Antique furniture filled the room.", "The antique clock still worked."],
  ["venerable", "adjective", "Accorded respect due to age", "The venerable oak shaded generations.", "Venerable traditions were honored."],
  ["timeworn", "adjective", "Impaired by time", "Timeworn steps led to the door.", "The timeworn book was fragile."],
  ["weathered", "adjective", "Worn by exposure to weather", "Weathered wood told of storms past.", "His weathered face showed experience."],
  ["rustic", "adjective", "Of or relating to the country", "Rustic charm characterized the cottage.", "Rustic furniture suited the cabin."],
  ["pastoral", "adjective", "Of country life or scenery", "Pastoral landscapes inspired the painter.", "The pastoral setting was peaceful."],
  ["bucolic", "adjective", "Relating to pleasant countryside", "Bucolic scenes filled her paintings.", "The bucolic life appealed to her."],
  ["agrarian", "adjective", "Relating to farming land", "Agrarian reforms changed the economy.", "Agrarian societies depended on harvests."],
  ["sylvan", "adjective", "Consisting of woods", "Sylvan paths wound through the forest.", "Sylvan creatures emerged at twilight."],
  ["wooded", "adjective", "Covered with trees", "Wooded hills surrounded the village.", "The wooded path was mysterious."],
  ["forested", "adjective", "Covered with forest", "Forested mountains rose in the distance.", "The forested valley was pristine."],
  ["verdant", "adjective", "Green with vegetation", "Verdant meadows stretched to the horizon.", "Spring brought verdant renewal."],
  ["lush", "adjective", "Growing luxuriantly", "Lush vegetation covered the island.", "The lush garden was paradise."],
  ["luxuriant", "adjective", "Rich and profuse in growth", "Luxuriant foliage filled the greenhouse.", "Her luxuriant hair cascaded down."],
  ["abundant", "adjective", "Existing in large quantities", "Abundant harvests blessed the year.", "Wildlife was abundant in the preserve."],
  ["copious", "adjective", "Abundant in supply", "Copious notes filled his journal.", "The copious rainfall flooded roads."],
  ["profuse", "adjective", "Abundantly plentiful", "Profuse apologies followed the mistake.", "Profuse blooms covered the garden."],
  ["lavish", "adjective", "Sumptuously rich", "Lavish decorations filled the ballroom.", "Lavish praise embarrassed her."],
  ["extravagant", "adjective", "Exceeding reasonable limits", "Extravagant spending depleted funds.", "The extravagant display impressed guests."],
  ["opulent", "adjective", "Ostentatiously luxurious", "Opulent mansions lined the avenue.", "The opulent feast amazed visitors."],
  ["sumptuous", "adjective", "Splendid and expensive", "A sumptuous banquet awaited guests.", "Sumptuous fabrics adorned the room."],
  ["palatial", "adjective", "Resembling a palace", "The palatial estate sprawled for acres.", "Palatial rooms dazzled visitors."],
  ["regal", "adjective", "Of or like a monarch", "Her regal bearing commanded respect.", "Regal ceremonies marked the occasion."],
  ["majestic", "adjective", "Having grandeur", "Majestic peaks touched the clouds.", "The majestic lion surveyed his realm."],
  ["stately", "adjective", "Having dignity and grandeur", "Stately elms lined the drive.", "A stately procession passed."],
  ["imposing", "adjective", "Grand and impressive", "The imposing castle dominated the landscape.", "His imposing presence silenced critics."],
  ["commanding", "adjective", "Indicating authority", "Her commanding voice captured attention.", "The commanding view was spectacular."],
  ["imperious", "adjective", "Assuming power or authority", "His imperious manner alienated colleagues.", "An imperious gesture dismissed them."],
  ["authoritative", "adjective", "Commanding and self-assured", "Her authoritative tone ended debate.", "Authoritative sources confirmed the news."],
  ["magisterial", "adjective", "Having authority or influence", "His magisterial work defined the field.", "A magisterial presence dominated the room."],
  ["pontifical", "adjective", "Pompously dogmatic", "His pontifical pronouncements bored listeners.", "The pontifical tone annoyed many."],
  ["bombastic", "adjective", "High-sounding but meaningless", "Bombastic speeches failed to convince.", "His bombastic style grated on nerves."],
  ["grandiloquent", "adjective", "Pompous in speech", "Grandiloquent rhetoric impressed few.", "His grandiloquent manner seemed artificial."],
  ["magniloquent", "adjective", "Speaking in a lofty style", "Magniloquent speeches marked the campaign.", "His magniloquent prose tired readers."],
  ["flowery", "adjective", "Full of elaborate phrases", "Flowery language obscured the meaning.", "Her flowery prose delighted some."],
  ["ornamental", "adjective", "Serving as decoration", "Ornamental plants bordered the walk.", "The ornamental design was beautiful."],
  ["decorative", "adjective", "Serving to decorate", "Decorative touches personalized the space.", "The decorative art was stunning."],
  ["aesthetic", "adjective", "Concerned with beauty", "Aesthetic considerations guided the design.", "Her aesthetic sense was impeccable."],
  ["artistic", "adjective", "Having natural creative skill", "Artistic flair characterized her work.", "The artistic community gathered."],
  ["creative", "adjective", "Relating to imagination", "Creative solutions emerged from discussion.", "Her creative energy was boundless."],
  ["imaginative", "adjective", "Having creative ability", "Imaginative play developed skills.", "His imaginative approach solved problems."],
  ["inventive", "adjective", "Having the ability to create", "Inventive minds drove progress.", "Her inventive cooking impressed guests."],
  ["innovative", "adjective", "Featuring new methods", "Innovative technology transformed industries.", "His innovative approach won acclaim."],
  ["original", "adjective", "Created directly; novel", "Original ideas were rewarded.", "Her original style was distinctive."],
  ["novel", "adjective", "New and unusual", "A novel approach was tried.", "Novel solutions were sought."],
  ["unique", "adjective", "Being the only one of its kind", "Her unique perspective was valued.", "Every snowflake is unique."],
  ["singular", "adjective", "Extraordinary; remarkable", "A singular achievement was recognized.", "His singular devotion impressed all."],
  ["uncommon", "adjective", "Out of the ordinary", "Uncommon wisdom guided her decisions.", "An uncommon opportunity arose."],
  ["rare", "adjective", "Not frequently found", "Rare books filled the collection.", "Such talent is rare indeed."],
  ["scarce", "adjective", "Insufficient for demand", "Water was scarce in the desert.", "Time became increasingly scarce."],
  ["precious", "adjective", "Of great value", "Precious memories were cherished.", "The precious gem sparkled."],
  ["invaluable", "adjective", "Extremely useful; priceless", "Her advice was invaluable.", "Invaluable experience prepared him."],
  ["priceless", "adjective", "So valuable it cannot be priced", "The priceless artifact was protected.", "Family moments are priceless."],
  ["treasured", "adjective", "Kept carefully as valuable", "Treasured memories sustained her.", "The treasured heirloom was passed down."],
  ["cherished", "adjective", "Held dear; beloved", "Cherished traditions continued.", "Her cherished dream came true."],
  ["beloved", "adjective", "Dearly loved", "The beloved teacher retired.", "Her beloved garden flourished."],
  ["adored", "adjective", "Loved and respected deeply", "The adored leader was mourned.", "She was adored by fans."],
  ["worshipped", "adjective", "Honored with religious rites", "The worshipped deity protected them.", "He was worshipped by followers."],
  ["idolized", "adjective", "Admired excessively", "The idolized star disappointed fans.", "She was idolized by youngsters."],
  ["revered", "adjective", "Deeply respected", "The revered master taught generations.", "Revered traditions were maintained."],
  ["hallowed", "adjective", "Made holy; revered", "Hallowed ground was protected.", "The hallowed tradition continued."],
  ["sacred", "adjective", "Connected with religion", "Sacred texts guided believers.", "The sacred place drew pilgrims."],
  ["divine", "adjective", "Of or like God", "Divine intervention was credited.", "The divine beauty inspired awe."],
  ["celestial", "adjective", "Positioned in the sky", "Celestial bodies moved in patterns.", "Celestial music filled the church."],
  ["heavenly", "adjective", "Of heaven; divine", "Heavenly voices sang hymns.", "The dessert was simply heavenly."],
  ["ethereal", "adjective", "Extremely delicate and light", "Ethereal beauty characterized the dancer.", "Ethereal mist covered the lake."],
  ["otherworldly", "adjective", "Relating to a supernatural world", "Otherworldly creatures populated the tale.", "The otherworldly glow puzzled scientists."],
  ["supernatural", "adjective", "Beyond natural explanation", "Supernatural events defied logic.", "The supernatural tale chilled readers."],
  ["mystical", "adjective", "Inspiring a sense of mystery", "Mystical symbols decorated the tomb.", "A mystical aura surrounded the shrine."],
  ["arcane", "adjective", "Understood by few", "Arcane knowledge was sought.", "Arcane rituals were performed."],
  ["esoteric", "adjective", "Intended for a select few", "Esoteric teachings attracted scholars.", "The esoteric text required translation."],
  ["cryptic", "adjective", "Having a meaning that is mysterious", "Cryptic messages puzzled investigators.", "His cryptic smile revealed nothing."],
  ["enigmatic", "adjective", "Difficult to interpret", "The enigmatic stranger intrigued them.", "Her enigmatic smile was famous."],
  ["inscrutable", "adjective", "Impossible to understand", "His inscrutable expression hid his thoughts.", "Inscrutable motives puzzled observers."],
  ["unfathomable", "adjective", "Incapable of being understood", "The universe's mysteries are unfathomable.", "Her unfathomable grief was private."],
  ["impenetrable", "adjective", "Impossible to understand", "The impenetrable jungle deterred explorers.", "His impenetrable calm was unnerving."],
  ["profound", "adjective", "Very great or intense", "Profound silence followed the news.", "His profound insights changed perspectives."],
  ["deep", "adjective", "Extending far down", "Deep thoughts occupied her mind.", "The deep well never ran dry."],
  ["abstruse", "adjective", "Difficult to understand", "Abstruse theories confused students.", "The abstruse text required annotation."],
  ["recondite", "adjective", "Little known; abstruse", "Recondite knowledge impressed scholars.", "The recondite subject attracted few."],
  ["obscure", "adjective", "Not discovered or known about", "Obscure references confused readers.", "The obscure artist deserved recognition."],
  ["opaque", "adjective", "Not able to be seen through", "Opaque glass provided privacy.", "His opaque explanations frustrated students."],
  ["nebulous", "adjective", "Unclear, vague, or undefined", "Nebulous plans worried investors.", "His nebulous ideas took shape slowly."],
  ["amorphous", "adjective", "Without a clearly defined form", "Amorphous shapes floated in the dream.", "The amorphous organization lacked structure."],
  ["formless", "adjective", "Without a definite form", "Formless fears haunted her nights.", "The formless mass took shape."],
  ["shapeless", "adjective", "Lacking a definite form", "The shapeless garment was comfortable.", "Shapeless clouds drifted overhead."],
  ["protean", "adjective", "Tending to change frequently", "His protean nature kept everyone guessing.", "The protean virus evolved rapidly."],
  ["mutable", "adjective", "Liable to change", "Human nature is mutable.", "Fashion is infinitely mutable."],
  ["mercurial", "adjective", "Subject to sudden changes of mood", "Her mercurial temperament was challenging.", "Mercurial weather marked the season."],
  ["capricious", "adjective", "Given to sudden changes of mood", "The capricious wind shifted constantly.", "Her capricious decisions frustrated colleagues."],
  ["fickle", "adjective", "Changing frequently", "Fickle tastes drove the market.", "The fickle public moved on quickly."],
  ["whimsical", "adjective", "Playfully quaint or fanciful", "Whimsical decorations charmed visitors.", "Her whimsical nature delighted children."],
  ["fantastical", "adjective", "Imaginary or fanciful", "Fantastical creatures populated the story.", "His fantastical tales entertained all."],
  ["fanciful", "adjective", "Overimaginative and unrealistic", "Fanciful notions amused him.", "Her fanciful designs won praise."],
  ["dreamlike", "adjective", "Having the quality of a dream", "The dreamlike sequence confused viewers.", "A dreamlike haze covered the scene."],
  ["surreal", "adjective", "Having a dreamlike quality", "The surreal landscape inspired artists.", "Events took a surreal turn."],
  ["bizarre", "adjective", "Very strange or unusual", "Bizarre behavior alarmed observers.", "The bizarre coincidence amazed everyone."],
  ["outlandish", "adjective", "Looking or sounding bizarre", "Outlandish costumes filled the parade.", "His outlandish claims were dismissed."],
  ["eccentric", "adjective", "Unconventional and strange", "Eccentric habits marked the genius.", "The eccentric millionaire lived alone."],
  ["peculiar", "adjective", "Strange or odd", "A peculiar smell filled the room.", "His peculiar manner intrigued visitors."],
  ["quaint", "adjective", "Attractively unusual or old-fashioned", "The quaint village attracted tourists.", "Quaint customs persisted in the region."],
  ["charming", "adjective", "Pleasant or attractive", "The charming inn welcomed travelers.", "Her charming manner won hearts."],
  ["delightful", "adjective", "Causing delight; very pleasant", "A delightful surprise awaited them.", "The delightful garden bloomed year-round."],
  ["lovely", "adjective", "Very beautiful or attractive", "A lovely melody filled the air.", "The lovely view inspired poets."],
  ["exquisite", "adjective", "Extremely beautiful and delicate", "Exquisite craftsmanship defined the piece.", "Her exquisite taste was admired."],
  ["elegant", "adjective", "Pleasingly graceful and stylish", "An elegant solution emerged.", "Her elegant manner impressed everyone."],
  ["graceful", "adjective", "Having elegance or beauty of movement", "The graceful dancer captivated audiences.", "A graceful arc defined the bridge."],
  ["fluid", "adjective", "Smoothly elegant or graceful", "Fluid movements characterized her dance.", "The fluid prose flowed beautifully."],
  ["flowing", "adjective", "Moving smoothly and continuously", "Flowing robes swirled around her.", "The flowing script was elegant."],
  ["sinuous", "adjective", "Having many curves and turns", "Sinuous paths climbed the mountain.", "Her sinuous dance mesmerized viewers."],
  ["serpentine", "adjective", "Winding and twisting like a snake", "The serpentine road tested drivers.", "Serpentine lines decorated the vase."],
  ["meandering", "adjective", "Following a winding course", "A meandering stream crossed the meadow.", "Their meandering conversation touched many topics."],
  ["winding", "adjective", "Following a twisting course", "Winding stairs led to the tower.", "The winding path revealed surprises."],
  ["labyrinthine", "adjective", "Like a labyrinth; complex", "Labyrinthine passages confused explorers.", "The labyrinthine plot bewildered readers."],
  ["intricate", "adjective", "Very complicated or detailed", "Intricate patterns decorated the rug.", "The intricate mechanism fascinated engineers."],
  ["elaborate", "adjective", "Involving many details", "Elaborate plans were made.", "The elaborate ceremony impressed guests."],
  ["complex", "adjective", "Consisting of many parts", "The complex system required expertise.", "Complex emotions filled her heart."],
  ["sophisticated", "adjective", "Having refined knowledge", "Sophisticated techniques were employed.", "Her sophisticated palate appreciated subtlety."],
  ["nuanced", "adjective", "Characterized by subtle differences", "Nuanced performances earned acclaim.", "The nuanced argument persuaded many."],
  ["subtle", "adjective", "Delicate or precise", "Subtle differences distinguished the wines.", "Her subtle humor escaped some."],
  ["understated", "adjective", "Presented with restraint", "Understated elegance defined her style.", "The understated design was effective."],
  ["refined", "adjective", "Elegant and cultured", "Refined tastes guided her choices.", "His refined manner charmed guests."],
  ["polished", "adjective", "Accomplished and skillful", "A polished performance concluded the show.", "His polished prose impressed editors."],
  ["cultivated", "adjective", "Refined and well-educated", "Cultivated tastes developed over time.", "The cultivated garden flourished."],
  ["cultured", "adjective", "Characterized by refined taste", "Cultured discussion followed dinner.", "Her cultured voice was soothing."],
  ["erudite", "adjective", "Having great knowledge", "Erudite commentary enriched the lecture.", "The erudite scholar published widely."],
  ["learned", "adjective", "Having much knowledge", "Learned discourse followed the reading.", "The learned professor was respected."],
  ["scholarly", "adjective", "Involving academic study", "Scholarly research revealed new findings.", "Her scholarly approach was rigorous."],
  ["academic", "adjective", "Relating to education and scholarship", "Academic achievement was celebrated.", "The academic community debated the theory."],
  ["intellectual", "adjective", "Relating to the intellect", "Intellectual pursuits occupied her time.", "The intellectual challenge excited him."],
  ["cerebral", "adjective", "Intellectual rather than emotional", "The cerebral film confused some.", "His cerebral approach impressed colleagues."],
  ["thoughtful", "adjective", "Absorbed in thought", "A thoughtful gift touched her.", "The thoughtful analysis was helpful."],
  ["reflective", "adjective", "Relating to deep thought", "Reflective moments came at sunset.", "Her reflective nature brought insights."],
  ["contemplative", "adjective", "Expressing deep thought", "A contemplative mood settled over her.", "The contemplative life attracted him."],
  ["meditative", "adjective", "Relating to meditation", "Meditative practice brought peace.", "Her meditative gaze was calming."],
  ["pensive", "adjective", "Engaged in deep thought", "A pensive expression crossed her face.", "Pensive silence followed the news."],
  ["introspective", "adjective", "Examining one's own thoughts", "Introspective journaling helped her.", "His introspective nature led to insights."],
  ["philosophical", "adjective", "Relating to philosophy", "Philosophical questions occupied his mind.", "Her philosophical approach was admired."],
  ["metaphysical", "adjective", "Relating to abstract thought", "Metaphysical poetry explored existence.", "Metaphysical questions have no easy answers."],
  ["transcendental", "adjective", "Beyond ordinary experience", "Transcendental meditation calmed her.", "The transcendental experience changed him."],
  ["spiritual", "adjective", "Relating to the human spirit", "Spiritual growth was her goal.", "The spiritual retreat refreshed him."],
  ["soulful", "adjective", "Expressing deep emotion", "Soulful music moved the audience.", "Her soulful eyes revealed her pain."],
  ["poignant", "adjective", "Evoking a keen sense of sadness", "A poignant moment silenced the room.", "The poignant scene brought tears."],
  ["moving", "adjective", "Producing strong emotion", "A moving tribute honored the hero.", "The moving speech touched everyone."],
  ["touching", "adjective", "Arousing feelings of sympathy", "A touching gesture warmed hearts.", "The touching story inspired many."],
  ["heartfelt", "adjective", "Sincere and deeply felt", "Heartfelt thanks were expressed.", "Her heartfelt apology was accepted."],
  ["sincere", "adjective", "Free from pretense", "Sincere wishes accompanied the gift.", "His sincere effort was appreciated."],
  ["genuine", "adjective", "Truly what it is said to be", "Genuine concern showed in her voice.", "The genuine article was rare."],
  ["authentic", "adjective", "Of undisputed origin", "Authentic artifacts filled the museum.", "Her authentic style was refreshing."],
  ["bona fide", "adjective", "Genuine; real", "A bona fide expert was consulted.", "The bona fide offer was accepted."],
  ["veritable", "adjective", "Used for emphasis", "A veritable feast awaited them.", "The garden was a veritable paradise."],
  ["definite", "adjective", "Clearly stated or decided", "A definite answer was given.", "Definite plans were made."],
  ["certain", "adjective", "Known for sure", "Certain facts were established.", "She was certain of her choice."],
  ["unequivocal", "adjective", "Leaving no doubt", "An unequivocal denial followed.", "Her unequivocal support was crucial."],
  ["unmistakable", "adjective", "Not able to be mistaken", "The unmistakable aroma of coffee drifted.", "His unmistakable style was recognized."],
  ["undeniable", "adjective", "Unable to be denied or disputed", "Undeniable evidence was presented.", "Her undeniable talent shone through."],
  ["irrefutable", "adjective", "Impossible to deny or disprove", "Irrefutable proof ended debate.", "The irrefutable logic convinced skeptics."],
  ["incontrovertible", "adjective", "Not able to be denied", "Incontrovertible facts were presented.", "The evidence was incontrovertible."],
  ["indisputable", "adjective", "Unable to be challenged", "The indisputable champion was crowned.", "Indisputable evidence sealed the case."],
  ["unquestionable", "adjective", "Not able to be disputed", "His unquestionable integrity was known.", "The unquestionable truth emerged."],
  ["manifest", "adjective", "Clear or obvious", "Manifest destiny drove expansion.", "Her manifest joy was contagious."],
  ["patent", "adjective", "Easily recognizable; obvious", "The patent absurdity was ignored.", "A patent lie was exposed."],
  ["transparent", "adjective", "Easy to perceive", "Transparent motives were obvious.", "The transparent excuse fooled no one."],
  ["lucid", "adjective", "Expressed clearly", "Lucid explanations helped students.", "His lucid writing was praised."],
  ["coherent", "adjective", "Logical and consistent", "A coherent argument was presented.", "Her coherent plan won approval."],
  ["articulate", "adjective", "Expressing oneself clearly", "An articulate spokesperson addressed the media.", "Her articulate defense impressed the jury."],
  ["eloquent", "adjective", "Fluent or persuasive", "Eloquent speeches moved the crowd.", "His eloquent plea won support."],
  ["expressive", "adjective", "Effectively conveying thought", "Expressive gestures enhanced the story.", "Her expressive face revealed emotions."],
  ["evocative", "adjective", "Bringing strong images or feelings", "Evocative music stirred memories.", "The evocative description transported readers."],
  ["suggestive", "adjective", "Tending to suggest an idea", "Suggestive imagery enriched the poem.", "The suggestive title intrigued readers."],
  ["resonant", "adjective", "Having the ability to evoke", "Resonant themes connected with audiences.", "The resonant voice filled the hall."],
  ["sonorous", "adjective", "Imposingly deep and full", "Sonorous bells marked the hour.", "His sonorous voice commanded attention."],
  ["mellifluous", "adjective", "Sweet-sounding", "Mellifluous tones charmed listeners.", "Her mellifluous voice was soothing."],
  ["dulcet", "adjective", "Sweet and soothing", "Dulcet sounds drifted from the garden.", "Her dulcet tones calmed the child."],
  ["harmonious", "adjective", "Free from disagreement", "Harmonious relations were restored.", "The harmonious blend pleased the ear."],
  ["melodious", "adjective", "Pleasant sounding; musical", "Melodious birdsong greeted the dawn.", "Her melodious laughter filled the room."],
  ["lyrical", "adjective", "Expressing emotion beautifully", "Lyrical prose characterized her style.", "The lyrical quality of his verse impressed."],
  ["rhythmic", "adjective", "Having a regular pattern", "Rhythmic drumming accompanied the dance.", "The rhythmic waves lulled her to sleep."],
  ["cadenced", "adjective", "Having rhythmic flow", "Cadenced steps marked the procession.", "His cadenced speech was hypnotic."],
  ["pulsating", "adjective", "Vibrating with energy", "Pulsating music filled the club.", "The pulsating city never slept."],
  ["throbbing", "adjective", "Beating with a strong rhythm", "Throbbing drums signaled celebration.", "A throbbing headache plagued him."],
  ["vibrant", "adjective", "Full of energy and enthusiasm", "Vibrant colors decorated the festival.", "The vibrant community welcomed newcomers."],
  ["dynamic", "adjective", "Characterized by constant change", "Dynamic performances captivated audiences.", "The dynamic market demanded adaptation."],
  ["kinetic", "adjective", "Relating to motion", "Kinetic energy powered the machine.", "Her kinetic style electrified audiences."],
  ["animated", "adjective", "Full of life and excitement", "Animated discussions followed the lecture.", "The animated film delighted children."],
  ["lively", "adjective", "Full of life and energy", "Lively debate ensued.", "The lively crowd cheered loudly."],
  ["spirited", "adjective", "Full of energy and courage", "Spirited defiance characterized the movement.", "A spirited performance earned applause."],
  ["vivacious", "adjective", "Attractively lively", "Her vivacious personality charmed everyone.", "The vivacious host kept spirits high."],
  ["sprightly", "adjective", "Lively and playful", "Sprightly tunes accompanied the dance.", "Despite his age, he remained sprightly."],
  ["perky", "adjective", "Cheerful and lively", "Her perky attitude was infectious.", "Perky music started the morning."],
  ["peppy", "adjective", "Lively and high-spirited", "The peppy tune got everyone moving.", "Her peppy energy inspired the team."],
  ["bouncy", "adjective", "Lively and cheerful", "Bouncy rhythms filled the room.", "Her bouncy personality cheered everyone."],
  ["bubbly", "adjective", "Full of cheerful high spirits", "Her bubbly nature attracted friends.", "Bubbly champagne celebrated the occasion."],
  ["chipper", "adjective", "Cheerful and lively", "He seemed chipper despite setbacks.", "A chipper attitude started each day."],
  ["jaunty", "adjective", "Having a lively manner", "A jaunty tune played on the radio.", "He walked with a jaunty step."],
  ["debonair", "adjective", "Confident, stylish, and charming", "The debonair host welcomed guests.", "His debonair manner charmed everyone."],
  ["dashing", "adjective", "Attractive and stylish", "The dashing hero rescued her.", "He cut a dashing figure."],
  ["dapper", "adjective", "Neat and trim in appearance", "The dapper gentleman turned heads.", "Always dapper, he impressed interviewers."],
  ["snappy", "adjective", "Cleverly concise; fashionably smart", "Snappy dialogue enlivened the film.", "His snappy dresser reputation was earned."],
  ["spiffy", "adjective", "Smart in appearance", "The spiffy new car impressed neighbors.", "He looked spiffy in his suit."],
  ["swanky", "adjective", "Stylishly luxurious", "The swanky restaurant intimidated some.", "Swanky hotels lined the boulevard."],
  ["ritzy", "adjective", "Ostentatiously stylish and luxurious", "The ritzy venue impressed guests.", "Ritzy neighborhoods commanded high prices."],
  ["posh", "adjective", "Elegant or stylishly luxurious", "Posh accents marked the upper class.", "The posh hotel exceeded expectations."],
  ["upscale", "adjective", "Relating to affluent consumers", "Upscale boutiques lined the street.", "The upscale restaurant required reservations."],
  ["classy", "adjective", "Stylish and sophisticated", "A classy event attracted elite guests.", "Her classy demeanor impressed everyone."],
  ["chic", "adjective", "Elegantly fashionable", "Chic boutiques attracted fashionistas.", "Her chic style was envied."],
  ["trendy", "adjective", "Very fashionable at the moment", "Trendy restaurants opened monthly.", "Trendy styles changed quickly."],
  ["fashionable", "adjective", "Characteristic of current popular trends", "Fashionable attire was expected.", "The fashionable district attracted visitors."],
  ["stylish", "adjective", "Having elegance and taste", "Stylish designs won awards.", "Her stylish apartment impressed guests."],
  ["modish", "adjective", "Conforming to current fashion", "Modish attire characterized the event.", "His modish appearance drew attention."],
  ["voguish", "adjective", "Following current fashion", "Voguish trends dominated the runway.", "Her voguish wardrobe cost a fortune."],
  ["sartorial", "adjective", "Relating to tailoring or clothes", "Sartorial elegance defined his style.", "Sartorial choices reflected personality."],
  ["couture", "noun", "The design and making of fashionable clothes", "Couture gowns graced the gala.", "Parisian couture set global trends."],
  ["bespoke", "adjective", "Made to individual order", "Bespoke suits fit perfectly.", "The bespoke service impressed clients."]
];

// Add new words if not already present
let addedCount = 0;
for (const [word, pos, definition, ex1, ex2] of additionalWords) {
  if (!existingSet.has(word.toLowerCase())) {
    existingWords.push({
      word,
      pos,
      definition,
      examples: [ex1, ex2]
    });
    existingSet.add(word.toLowerCase());
    addedCount++;
  }
}

console.log(`Added ${addedCount} new words. Total: ${existingWords.length}`);

// Save updated words
writeFileSync(dataPath, JSON.stringify(existingWords, null, 2));
console.log('Words file updated successfully!');

